-- Generated by Prisma migrate diff. Source: prisma/base.prisma (sqlite).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_base_audit_entries" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "operation_id" TEXT NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "request_hostname" TEXT NOT NULL DEFAULT '',
    "request_path" TEXT NOT NULL DEFAULT '',
    "table_name" TEXT NOT NULL,
    "row_id" BIGINT NOT NULL,
    "action" TEXT NOT NULL,
    "changes" TEXT NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'applied',
    "reviewed_at" BIGINT,
    "reviewed_duid" BIGINT,
    "review_reason" TEXT NOT NULL DEFAULT '',
    "reverted_at" BIGINT,
    "reverted_duid" BIGINT,
    "revert_reason" TEXT NOT NULL DEFAULT '',
    "restored_at" BIGINT,
    "restored_duid" BIGINT,
    "restore_reason" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_base_audit_entries" ("action", "changes", "created_at", "created_duid", "deleted_at", "id", "operation_id", "owner_bid", "owner_tid", "owner_uid", "reason", "restore_reason", "restored_at", "restored_duid", "revert_reason", "reverted_at", "reverted_duid", "review_reason", "reviewed_at", "reviewed_duid", "row_id", "status", "table_name", "updated_at", "updated_duid") SELECT "action", "changes", "created_at", "created_duid", "deleted_at", "id", "operation_id", "owner_bid", "owner_tid", "owner_uid", "reason", "restore_reason", "restored_at", "restored_duid", "revert_reason", "reverted_at", "reverted_duid", "review_reason", "reviewed_at", "reviewed_duid", "row_id", "status", "table_name", "updated_at", "updated_duid" FROM "base_audit_entries";
DROP TABLE "base_audit_entries";
ALTER TABLE "new_base_audit_entries" RENAME TO "base_audit_entries";
CREATE INDEX "base_audit_entries_owner_tid_created_at_idx" ON "base_audit_entries"("owner_tid", "created_at");
CREATE INDEX "base_audit_entries_owner_bid_created_at_idx" ON "base_audit_entries"("owner_bid", "created_at");
CREATE INDEX "base_audit_entries_owner_uid_created_at_idx" ON "base_audit_entries"("owner_uid", "created_at");
CREATE INDEX "base_audit_entries_table_name_row_id_created_at_idx" ON "base_audit_entries"("table_name", "row_id", "created_at");
CREATE INDEX "base_audit_entries_operation_id_idx" ON "base_audit_entries"("operation_id");
CREATE INDEX "base_audit_entries_status_created_at_idx" ON "base_audit_entries"("status", "created_at");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
