-- Generated by Prisma migrate diff. Source: prisma/base.prisma (sqlite).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_base_tenants" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_base_tenants" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "status", "title", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "status", "title", "updated_at", "updated_duid" FROM "base_tenants";
DROP TABLE "base_tenants";
ALTER TABLE "new_base_tenants" RENAME TO "base_tenants";
CREATE UNIQUE INDEX "base_tenants_key_key" ON "base_tenants"("key");
CREATE UNIQUE INDEX "base_tenants_name_deleted_at_key" ON "base_tenants"("name", "deleted_at");
CREATE TABLE "new_base_branches" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_base_branches" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "status", "title", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "status", "title", "updated_at", "updated_duid" FROM "base_branches";
DROP TABLE "base_branches";
ALTER TABLE "new_base_branches" RENAME TO "base_branches";
CREATE UNIQUE INDEX "base_branches_key_key" ON "base_branches"("key");
CREATE UNIQUE INDEX "base_branches_owner_tid_name_deleted_at_key" ON "base_branches"("owner_tid", "name", "deleted_at");
CREATE TABLE "new_base_configs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "value" TEXT NOT NULL
);
INSERT INTO "new_base_configs" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "updated_at", "updated_duid", "value") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "updated_at", "updated_duid", "value" FROM "base_configs";
DROP TABLE "base_configs";
ALTER TABLE "new_base_configs" RENAME TO "base_configs";
CREATE UNIQUE INDEX "base_configs_key_key" ON "base_configs"("key");
CREATE UNIQUE INDEX "base_configs_owner_tid_name_deleted_at_key" ON "base_configs"("owner_tid", "name", "deleted_at");
CREATE TABLE "new_base_bootstrap" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "value" TEXT NOT NULL
);
INSERT INTO "new_base_bootstrap" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "updated_at", "updated_duid", "value") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pended_at", "updated_at", "updated_duid", "value" FROM "base_bootstrap";
DROP TABLE "base_bootstrap";
ALTER TABLE "new_base_bootstrap" RENAME TO "base_bootstrap";
CREATE UNIQUE INDEX "base_bootstrap_key_key" ON "base_bootstrap"("key");
CREATE UNIQUE INDEX "base_bootstrap_owner_tid_name_deleted_at_key" ON "base_bootstrap"("owner_tid", "name", "deleted_at");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
