-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "pve_regions_code_deleted_at_key";

-- AlterTable
ALTER TABLE "pve_regions" DROP COLUMN "code",
DROP COLUMN "display_name",
DROP COLUMN "name",
ADD COLUMN     "key" TEXT NOT NULL,
ADD COLUMN     "title" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "pve_instance_flavors" DROP COLUMN "code",
DROP COLUMN "name",
ADD COLUMN     "key" TEXT NOT NULL,
ADD COLUMN     "title" TEXT NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "pve_regions_key_deleted_at_key" ON "pve_regions"("key", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "pve_instance_flavors_key_deleted_at_key" ON "pve_instance_flavors"("key", "deleted_at");
