-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE "pve_regions" ALTER COLUMN "key" SET DATA TYPE VARCHAR(36);

-- AlterTable
ALTER TABLE "pve_nodes" ADD COLUMN     "key" VARCHAR(36) NOT NULL;

-- AlterTable
ALTER TABLE "pve_instance_flavors" ALTER COLUMN "key" SET DATA TYPE VARCHAR(36);

-- AlterTable
ALTER TABLE "pve_vms" ADD COLUMN     "key" VARCHAR(36) NOT NULL;

-- AlterTable
ALTER TABLE "pve_vm_tasks" ADD COLUMN     "key" VARCHAR(36) NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "pve_nodes_key_deleted_at_key" ON "pve_nodes"("key", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "pve_vms_key_deleted_at_key" ON "pve_vms"("key", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "pve_vm_tasks_key_deleted_at_key" ON "pve_vm_tasks"("key", "deleted_at");
