-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "pve_instance_flavors_cpu_cores_memory_gb_deleted_at_key";

-- DropIndex
DROP INDEX "pve_vm_tasks_idempotency_key_deleted_at_key";

-- CreateIndex
CREATE UNIQUE INDEX "pve_instance_flavors_cpu_cores_memory_gb_key" ON "pve_instance_flavors"("cpu_cores", "memory_gb");

-- CreateIndex
CREATE UNIQUE INDEX "pve_vm_tasks_idempotency_key_key" ON "pve_vm_tasks"("idempotency_key");
