-- Generated by Prisma migrate diff. Source: prisma/global.prisma (sqlite).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_global_sites" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "base_site_key" TEXT,
    "dsn" TEXT NOT NULL DEFAULT '',
    "dsn_password" TEXT,
    "database_binding" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "migration_status" TEXT NOT NULL DEFAULT 'ready',
    "is_default" INTEGER NOT NULL DEFAULT 0,
    "is_system" INTEGER NOT NULL DEFAULT 0,
    "passport_sso_enabled" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_global_sites" ("base_site_key", "created_at", "created_duid", "database_binding", "deleted_at", "dsn", "dsn_password", "id", "is_default", "is_system", "key", "migration_status", "owner_bid", "owner_tid", "owner_uid", "passport_sso_enabled", "status", "title", "updated_at", "updated_duid") SELECT "base_site_key", "created_at", "created_duid", "database_binding", "deleted_at", "dsn", "dsn_password", "id", "is_default", "is_system", "key", "migration_status", "owner_bid", "owner_tid", "owner_uid", "passport_sso_enabled", "status", "title", "updated_at", "updated_duid" FROM "global_sites";
DROP TABLE "global_sites";
ALTER TABLE "new_global_sites" RENAME TO "global_sites";
CREATE UNIQUE INDEX "global_sites_key_deleted_at_key" ON "global_sites"("key", "deleted_at");
CREATE TABLE "new_global_site_hosts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "hostname" TEXT NOT NULL,
    "site_key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_site_hosts" ("created_at", "created_duid", "deleted_at", "hostname", "id", "key", "owner_bid", "owner_tid", "owner_uid", "site_key", "status", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "hostname", "id", "key", "owner_bid", "owner_tid", "owner_uid", "site_key", "status", "updated_at", "updated_duid" FROM "global_site_hosts";
DROP TABLE "global_site_hosts";
ALTER TABLE "new_global_site_hosts" RENAME TO "global_site_hosts";
CREATE UNIQUE INDEX "global_site_hosts_hostname_deleted_at_key" ON "global_site_hosts"("hostname", "deleted_at");
CREATE UNIQUE INDEX "global_site_hosts_key_deleted_at_key" ON "global_site_hosts"("key", "deleted_at");
CREATE TABLE "new_global_cloud_credentials" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "account_id" TEXT NOT NULL DEFAULT '',
    "access_key_id" TEXT NOT NULL DEFAULT '',
    "access_key_secret" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_credentials" ("access_key_id", "access_key_secret", "account_id", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider", "status", "title", "updated_at", "updated_duid") SELECT "access_key_id", "access_key_secret", "account_id", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider", "status", "title", "updated_at", "updated_duid" FROM "global_cloud_credentials";
DROP TABLE "global_cloud_credentials";
ALTER TABLE "new_global_cloud_credentials" RENAME TO "global_cloud_credentials";
CREATE UNIQUE INDEX "global_cloud_credentials_title_deleted_at_key" ON "global_cloud_credentials"("title", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_credentials_key_deleted_at_key" ON "global_cloud_credentials"("key", "deleted_at");
CREATE TABLE "new_global_cloud_object_storage_buckets" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "cloud_credential_id" BIGINT NOT NULL,
    "endpoint" TEXT NOT NULL,
    "region" TEXT NOT NULL DEFAULT '',
    "bucket" TEXT NOT NULL,
    "path_style" INTEGER NOT NULL DEFAULT 0,
    "public_base_url" TEXT NOT NULL DEFAULT '',
    "extra_config" TEXT NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_object_storage_buckets" ("bucket", "cloud_credential_id", "created_at", "created_duid", "deleted_at", "endpoint", "extra_config", "id", "key", "owner_bid", "owner_tid", "owner_uid", "path_style", "public_base_url", "region", "status", "updated_at", "updated_duid") SELECT "bucket", "cloud_credential_id", "created_at", "created_duid", "deleted_at", "endpoint", "extra_config", "id", "key", "owner_bid", "owner_tid", "owner_uid", "path_style", "public_base_url", "region", "status", "updated_at", "updated_duid" FROM "global_cloud_object_storage_buckets";
DROP TABLE "global_cloud_object_storage_buckets";
ALTER TABLE "new_global_cloud_object_storage_buckets" RENAME TO "global_cloud_object_storage_buckets";
CREATE UNIQUE INDEX "global_cloud_object_storage_buckets_cloud_credential_id_endpoint_bucket_deleted_at_key" ON "global_cloud_object_storage_buckets"("cloud_credential_id", "endpoint", "bucket", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_object_storage_buckets_key_deleted_at_key" ON "global_cloud_object_storage_buckets"("key", "deleted_at");
CREATE TABLE "new_global_cloud_object_storage_bindings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "site_key" TEXT NOT NULL,
    "bucket_id" BIGINT NOT NULL,
    "key_prefix" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_object_storage_bindings" ("bucket_id", "created_at", "created_duid", "deleted_at", "id", "key", "key_prefix", "owner_bid", "owner_tid", "owner_uid", "site_key", "status", "updated_at", "updated_duid") SELECT "bucket_id", "created_at", "created_duid", "deleted_at", "id", "key", "key_prefix", "owner_bid", "owner_tid", "owner_uid", "site_key", "status", "updated_at", "updated_duid" FROM "global_cloud_object_storage_bindings";
DROP TABLE "global_cloud_object_storage_bindings";
ALTER TABLE "new_global_cloud_object_storage_bindings" RENAME TO "global_cloud_object_storage_bindings";
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_id_site_key_deleted_at_key" ON "global_cloud_object_storage_bindings"("id", "site_key", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_site_key_bucket_id_key_prefix_deleted_at_key" ON "global_cloud_object_storage_bindings"("site_key", "bucket_id", "key_prefix", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_key_deleted_at_key" ON "global_cloud_object_storage_bindings"("key", "deleted_at");
CREATE TABLE "new_global_cloud_object_storage_binding_purposes" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "binding_id" BIGINT NOT NULL,
    "site_key" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "is_default" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_global_cloud_object_storage_binding_purposes" ("binding_id", "created_at", "created_duid", "deleted_at", "id", "is_default", "key", "owner_bid", "owner_tid", "owner_uid", "purpose", "site_key", "updated_at", "updated_duid") SELECT "binding_id", "created_at", "created_duid", "deleted_at", "id", "is_default", "key", "owner_bid", "owner_tid", "owner_uid", "purpose", "site_key", "updated_at", "updated_duid" FROM "global_cloud_object_storage_binding_purposes";
DROP TABLE "global_cloud_object_storage_binding_purposes";
ALTER TABLE "new_global_cloud_object_storage_binding_purposes" RENAME TO "global_cloud_object_storage_binding_purposes";
CREATE UNIQUE INDEX "global_cloud_object_storage_binding_purposes_binding_id_purpose_deleted_at_key" ON "global_cloud_object_storage_binding_purposes"("binding_id", "purpose", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_object_storage_binding_purposes_key_deleted_at_key" ON "global_cloud_object_storage_binding_purposes"("key", "deleted_at");
CREATE TABLE "new_global_telegram_bots" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "secret_token" TEXT NOT NULL,
    "webhook_hostname" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_telegram_bots" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "secret_token", "status", "title", "token", "updated_at", "updated_duid", "username", "webhook_hostname") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "secret_token", "status", "title", "token", "updated_at", "updated_duid", "username", "webhook_hostname" FROM "global_telegram_bots";
DROP TABLE "global_telegram_bots";
ALTER TABLE "new_global_telegram_bots" RENAME TO "global_telegram_bots";
CREATE INDEX "global_telegram_bots_webhook_hostname_idx" ON "global_telegram_bots"("webhook_hostname");
CREATE UNIQUE INDEX "global_telegram_bots_title_deleted_at_key" ON "global_telegram_bots"("title", "deleted_at");
CREATE UNIQUE INDEX "global_telegram_bots_token_deleted_at_key" ON "global_telegram_bots"("token", "deleted_at");
CREATE UNIQUE INDEX "global_telegram_bots_username_deleted_at_key" ON "global_telegram_bots"("username", "deleted_at");
CREATE UNIQUE INDEX "global_telegram_bots_key_deleted_at_key" ON "global_telegram_bots"("key", "deleted_at");
CREATE TABLE "new_global_cloud_email_channels" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "cloud_credential_id" BIGINT NOT NULL,
    "region" TEXT NOT NULL,
    "account_name" TEXT NOT NULL,
    "from_alias" TEXT NOT NULL,
    "reply_to_address" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_email_channels" ("account_name", "cloud_credential_id", "created_at", "created_duid", "deleted_at", "from_alias", "id", "key", "owner_bid", "owner_tid", "owner_uid", "region", "reply_to_address", "status", "updated_at", "updated_duid") SELECT "account_name", "cloud_credential_id", "created_at", "created_duid", "deleted_at", "from_alias", "id", "key", "owner_bid", "owner_tid", "owner_uid", "region", "reply_to_address", "status", "updated_at", "updated_duid" FROM "global_cloud_email_channels";
DROP TABLE "global_cloud_email_channels";
ALTER TABLE "new_global_cloud_email_channels" RENAME TO "global_cloud_email_channels";
CREATE UNIQUE INDEX "global_cloud_email_channels_cloud_credential_id_region_account_name_deleted_at_key" ON "global_cloud_email_channels"("cloud_credential_id", "region", "account_name", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_email_channels_key_deleted_at_key" ON "global_cloud_email_channels"("key", "deleted_at");
CREATE TABLE "new_global_cloud_email_templates" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "type" TEXT NOT NULL DEFAULT 'email_verification',
    "title" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "body_html" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_email_templates" ("body_html", "body_text", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "subject", "title", "type", "updated_at", "updated_duid") SELECT "body_html", "body_text", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "subject", "title", "type", "updated_at", "updated_duid" FROM "global_cloud_email_templates";
DROP TABLE "global_cloud_email_templates";
ALTER TABLE "new_global_cloud_email_templates" RENAME TO "global_cloud_email_templates";
CREATE UNIQUE INDEX "global_cloud_email_templates_key_deleted_at_key" ON "global_cloud_email_templates"("key", "deleted_at");
CREATE TABLE "new_global_cloud_email_bindings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "site_key" TEXT NOT NULL,
    "channel_id" BIGINT NOT NULL,
    "template_id" BIGINT NOT NULL,
    "purpose" TEXT NOT NULL,
    "is_default" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_email_bindings" ("channel_id", "created_at", "created_duid", "deleted_at", "id", "is_default", "key", "owner_bid", "owner_tid", "owner_uid", "purpose", "site_key", "status", "template_id", "updated_at", "updated_duid") SELECT "channel_id", "created_at", "created_duid", "deleted_at", "id", "is_default", "key", "owner_bid", "owner_tid", "owner_uid", "purpose", "site_key", "status", "template_id", "updated_at", "updated_duid" FROM "global_cloud_email_bindings";
DROP TABLE "global_cloud_email_bindings";
ALTER TABLE "new_global_cloud_email_bindings" RENAME TO "global_cloud_email_bindings";
CREATE UNIQUE INDEX "global_cloud_email_bindings_site_key_channel_id_template_id_purpose_deleted_at_key" ON "global_cloud_email_bindings"("site_key", "channel_id", "template_id", "purpose", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_email_bindings_key_deleted_at_key" ON "global_cloud_email_bindings"("key", "deleted_at");
CREATE TABLE "new_global_cloud_email_template_publications" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "template_id" BIGINT NOT NULL,
    "cloud_credential_id" BIGINT NOT NULL,
    "region" TEXT NOT NULL,
    "provider_template_id" TEXT NOT NULL,
    "content_hash" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL
);
INSERT INTO "new_global_cloud_email_template_publications" ("cloud_credential_id", "content_hash", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider_template_id", "region", "status", "template_id", "updated_at", "updated_duid") SELECT "cloud_credential_id", "content_hash", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider_template_id", "region", "status", "template_id", "updated_at", "updated_duid" FROM "global_cloud_email_template_publications";
DROP TABLE "global_cloud_email_template_publications";
ALTER TABLE "new_global_cloud_email_template_publications" RENAME TO "global_cloud_email_template_publications";
CREATE UNIQUE INDEX "global_cloud_email_template_publications_template_id_cloud_credential_id_region_deleted_at_key" ON "global_cloud_email_template_publications"("template_id", "cloud_credential_id", "region", "deleted_at");
CREATE UNIQUE INDEX "global_cloud_email_template_publications_key_deleted_at_key" ON "global_cloud_email_template_publications"("key", "deleted_at");
CREATE TABLE "new_global_snowflake_state" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "worker_id" INTEGER NOT NULL,
    "last_timestamp" BIGINT NOT NULL
);
INSERT INTO "new_global_snowflake_state" ("created_at", "created_duid", "deleted_at", "id", "last_timestamp", "owner_bid", "owner_tid", "owner_uid", "updated_at", "updated_duid", "worker_id") SELECT "created_at", "created_duid", "deleted_at", "id", "last_timestamp", "owner_bid", "owner_tid", "owner_uid", "updated_at", "updated_duid", "worker_id" FROM "global_snowflake_state";
DROP TABLE "global_snowflake_state";
ALTER TABLE "new_global_snowflake_state" RENAME TO "global_snowflake_state";
CREATE UNIQUE INDEX "global_snowflake_state_worker_id_deleted_at_key" ON "global_snowflake_state"("worker_id", "deleted_at");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
