-- Generated by Prisma migrate diff. Source: prisma/passport.prisma (sqlite).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_passport_users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_passport_users" ("created_at", "created_duid", "deleted_at", "id", "key", "name", "owner_bid", "owner_tid", "owner_uid", "status", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "name", "owner_bid", "owner_tid", "owner_uid", "status", "updated_at", "updated_duid" FROM "passport_users";
DROP TABLE "passport_users";
ALTER TABLE "new_passport_users" RENAME TO "passport_users";
CREATE UNIQUE INDEX "passport_users_key_deleted_at_key" ON "passport_users"("key", "deleted_at");
CREATE UNIQUE INDEX "passport_users_name_deleted_at_key" ON "passport_users"("name", "deleted_at");
CREATE TABLE "new_passport_user_email_otps" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "otp_id" TEXT NOT NULL,
    "user_key" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_user_email_otps" ("attempt_count", "code_hash", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "otp_id", "owner_bid", "owner_tid", "owner_uid", "status", "updated_at", "updated_duid", "user_key") SELECT "attempt_count", "code_hash", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "otp_id", "owner_bid", "owner_tid", "owner_uid", "status", "updated_at", "updated_duid", "user_key" FROM "passport_user_email_otps";
DROP TABLE "passport_user_email_otps";
ALTER TABLE "new_passport_user_email_otps" RENAME TO "passport_user_email_otps";
CREATE INDEX "passport_user_email_otps_user_key_status_created_at_idx" ON "passport_user_email_otps"("user_key", "status", "created_at");
CREATE UNIQUE INDEX "passport_user_email_otps_otp_id_deleted_at_key" ON "passport_user_email_otps"("otp_id", "deleted_at");
CREATE UNIQUE INDEX "passport_user_email_otps_key_deleted_at_key" ON "passport_user_email_otps"("key", "deleted_at");
CREATE TABLE "new_passport_user_credentials" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" TEXT NOT NULL,
    "password" TEXT NOT NULL
);
INSERT INTO "new_passport_user_credentials" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "password", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "password", "updated_at", "updated_duid", "user_key" FROM "passport_user_credentials";
DROP TABLE "passport_user_credentials";
ALTER TABLE "new_passport_user_credentials" RENAME TO "passport_user_credentials";
CREATE INDEX "passport_user_credentials_user_key_created_at_id_idx" ON "passport_user_credentials"("user_key", "created_at", "id");
CREATE UNIQUE INDEX "passport_user_credentials_key_deleted_at_key" ON "passport_user_credentials"("key", "deleted_at");
CREATE TABLE "new_passport_sessions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "user_key" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "device_id" BIGINT NOT NULL
);
INSERT INTO "new_passport_sessions" ("created_at", "created_duid", "deleted_at", "device_id", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "token_hash", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "device_id", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "token_hash", "updated_at", "updated_duid", "user_key" FROM "passport_sessions";
DROP TABLE "passport_sessions";
ALTER TABLE "new_passport_sessions" RENAME TO "passport_sessions";
CREATE INDEX "passport_sessions_user_key_idx" ON "passport_sessions"("user_key");
CREATE INDEX "passport_sessions_expires_at_idx" ON "passport_sessions"("expires_at");
CREATE UNIQUE INDEX "passport_sessions_token_hash_deleted_at_key" ON "passport_sessions"("token_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_sessions_key_deleted_at_key" ON "passport_sessions"("key", "deleted_at");
CREATE TABLE "new_passport_devices" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "fingerprint" TEXT NOT NULL DEFAULT '{}',
    "user_agent" TEXT NOT NULL DEFAULT '',
    "platform" TEXT NOT NULL DEFAULT '',
    "ip_address" TEXT NOT NULL DEFAULT '',
    "network_info" TEXT NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT
);
INSERT INTO "new_passport_devices" ("created_at", "created_duid", "deleted_at", "fingerprint", "id", "ip_address", "key", "last_seen_at", "network_info", "owner_bid", "owner_tid", "owner_uid", "platform", "revoked_at", "status", "updated_at", "updated_duid", "user_agent") SELECT "created_at", "created_duid", "deleted_at", "fingerprint", "id", "ip_address", "key", "last_seen_at", "network_info", "owner_bid", "owner_tid", "owner_uid", "platform", "revoked_at", "status", "updated_at", "updated_duid", "user_agent" FROM "passport_devices";
DROP TABLE "passport_devices";
ALTER TABLE "new_passport_devices" RENAME TO "passport_devices";
CREATE UNIQUE INDEX "passport_devices_key_deleted_at_key" ON "passport_devices"("key", "deleted_at");
CREATE TABLE "new_passport_device_users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "user_key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT
);
INSERT INTO "new_passport_device_users" ("created_at", "created_duid", "deleted_at", "device_id", "id", "key", "last_seen_at", "owner_bid", "owner_tid", "owner_uid", "revoked_at", "status", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "device_id", "id", "key", "last_seen_at", "owner_bid", "owner_tid", "owner_uid", "revoked_at", "status", "updated_at", "updated_duid", "user_key" FROM "passport_device_users";
DROP TABLE "passport_device_users";
ALTER TABLE "new_passport_device_users" RENAME TO "passport_device_users";
CREATE UNIQUE INDEX "passport_device_users_device_id_user_key_deleted_at_key" ON "passport_device_users"("device_id", "user_key", "deleted_at");
CREATE UNIQUE INDEX "passport_device_users_key_deleted_at_key" ON "passport_device_users"("key", "deleted_at");
CREATE TABLE "new_passport_telegram_accounts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" TEXT NOT NULL,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "nickname" TEXT NOT NULL
);
INSERT INTO "new_passport_telegram_accounts" ("bot_id", "chat_id", "created_at", "created_duid", "deleted_at", "id", "key", "nickname", "owner_bid", "owner_tid", "owner_uid", "telegram_user_id", "updated_at", "updated_duid", "user_key") SELECT "bot_id", "chat_id", "created_at", "created_duid", "deleted_at", "id", "key", "nickname", "owner_bid", "owner_tid", "owner_uid", "telegram_user_id", "updated_at", "updated_duid", "user_key" FROM "passport_telegram_accounts";
DROP TABLE "passport_telegram_accounts";
ALTER TABLE "new_passport_telegram_accounts" RENAME TO "passport_telegram_accounts";
CREATE UNIQUE INDEX "passport_telegram_accounts_bot_id_telegram_user_id_deleted_at_key" ON "passport_telegram_accounts"("bot_id", "telegram_user_id", "deleted_at");
CREATE UNIQUE INDEX "passport_telegram_accounts_key_deleted_at_key" ON "passport_telegram_accounts"("key", "deleted_at");
CREATE TABLE "new_passport_oauth_accounts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "provider_user_id" TEXT NOT NULL
);
INSERT INTO "new_passport_oauth_accounts" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider", "provider_user_id", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider", "provider_user_id", "updated_at", "updated_duid", "user_key" FROM "passport_oauth_accounts";
DROP TABLE "passport_oauth_accounts";
ALTER TABLE "new_passport_oauth_accounts" RENAME TO "passport_oauth_accounts";
CREATE UNIQUE INDEX "passport_oauth_accounts_provider_provider_user_id_deleted_at_key" ON "passport_oauth_accounts"("provider", "provider_user_id", "deleted_at");
CREATE UNIQUE INDEX "passport_oauth_accounts_key_deleted_at_key" ON "passport_oauth_accounts"("key", "deleted_at");
CREATE TABLE "new_passport_emails" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "email" TEXT NOT NULL,
    "verified" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_passport_emails" ("created_at", "created_duid", "deleted_at", "email", "id", "key", "owner_bid", "owner_tid", "owner_uid", "updated_at", "updated_duid", "verified") SELECT "created_at", "created_duid", "deleted_at", "email", "id", "key", "owner_bid", "owner_tid", "owner_uid", "updated_at", "updated_duid", "verified" FROM "passport_emails";
DROP TABLE "passport_emails";
ALTER TABLE "new_passport_emails" RENAME TO "passport_emails";
CREATE UNIQUE INDEX "passport_emails_email_deleted_at_key" ON "passport_emails"("email", "deleted_at");
CREATE UNIQUE INDEX "passport_emails_key_deleted_at_key" ON "passport_emails"("key", "deleted_at");
CREATE TABLE "new_passport_user_emails" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" TEXT NOT NULL,
    "email_id" BIGINT NOT NULL,
    "is_primary" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_passport_user_emails" ("created_at", "created_duid", "deleted_at", "email_id", "id", "is_primary", "key", "owner_bid", "owner_tid", "owner_uid", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "email_id", "id", "is_primary", "key", "owner_bid", "owner_tid", "owner_uid", "updated_at", "updated_duid", "user_key" FROM "passport_user_emails";
DROP TABLE "passport_user_emails";
ALTER TABLE "new_passport_user_emails" RENAME TO "passport_user_emails";
CREATE UNIQUE INDEX "passport_user_emails_user_key_email_id_deleted_at_key" ON "passport_user_emails"("user_key", "email_id", "deleted_at");
CREATE UNIQUE INDEX "passport_user_emails_email_id_deleted_at_key" ON "passport_user_emails"("email_id", "deleted_at");
CREATE UNIQUE INDEX "passport_user_emails_key_deleted_at_key" ON "passport_user_emails"("key", "deleted_at");
CREATE TABLE "new_passport_email_otp" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "email" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_email_otp" ("attempt_count", "bot_id", "chat_id", "code_hash", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "telegram_user_id", "updated_at", "updated_duid") SELECT "attempt_count", "bot_id", "chat_id", "code_hash", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "telegram_user_id", "updated_at", "updated_duid" FROM "passport_email_otp";
DROP TABLE "passport_email_otp";
ALTER TABLE "new_passport_email_otp" RENAME TO "passport_email_otp";
CREATE INDEX "passport_email_otp_bot_id_telegram_user_id_status_created_at_idx" ON "passport_email_otp"("bot_id", "telegram_user_id", "status", "created_at");
CREATE UNIQUE INDEX "passport_email_otp_key_deleted_at_key" ON "passport_email_otp"("key", "deleted_at");
CREATE TABLE "new_passport_telegram_menus" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "message_id" BIGINT NOT NULL,
    "mode" TEXT NOT NULL
);
INSERT INTO "new_passport_telegram_menus" ("bot_id", "chat_id", "created_at", "created_duid", "deleted_at", "id", "key", "message_id", "mode", "owner_bid", "owner_tid", "owner_uid", "telegram_user_id", "updated_at", "updated_duid") SELECT "bot_id", "chat_id", "created_at", "created_duid", "deleted_at", "id", "key", "message_id", "mode", "owner_bid", "owner_tid", "owner_uid", "telegram_user_id", "updated_at", "updated_duid" FROM "passport_telegram_menus";
DROP TABLE "passport_telegram_menus";
ALTER TABLE "new_passport_telegram_menus" RENAME TO "passport_telegram_menus";
CREATE UNIQUE INDEX "passport_telegram_menus_bot_id_telegram_user_id_deleted_at_key" ON "passport_telegram_menus"("bot_id", "telegram_user_id", "deleted_at");
CREATE UNIQUE INDEX "passport_telegram_menus_key_deleted_at_key" ON "passport_telegram_menus"("key", "deleted_at");
CREATE TABLE "new_passport_telegram_updates" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "update_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL
);
INSERT INTO "new_passport_telegram_updates" ("bot_id", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "update_id", "updated_at", "updated_duid") SELECT "bot_id", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "update_id", "updated_at", "updated_duid" FROM "passport_telegram_updates";
DROP TABLE "passport_telegram_updates";
ALTER TABLE "new_passport_telegram_updates" RENAME TO "passport_telegram_updates";
CREATE INDEX "passport_telegram_updates_status_updated_at_idx" ON "passport_telegram_updates"("status", "updated_at");
CREATE UNIQUE INDEX "passport_telegram_updates_bot_id_update_id_deleted_at_key" ON "passport_telegram_updates"("bot_id", "update_id", "deleted_at");
CREATE UNIQUE INDEX "passport_telegram_updates_key_deleted_at_key" ON "passport_telegram_updates"("key", "deleted_at");
CREATE TABLE "new_passport_telegram_identity_choices" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "target_user_key" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_telegram_identity_choices" ("bot_id", "chat_id", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "target_user_key", "telegram_user_id", "updated_at", "updated_duid") SELECT "bot_id", "chat_id", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "target_user_key", "telegram_user_id", "updated_at", "updated_duid" FROM "passport_telegram_identity_choices";
DROP TABLE "passport_telegram_identity_choices";
ALTER TABLE "new_passport_telegram_identity_choices" RENAME TO "passport_telegram_identity_choices";
CREATE INDEX "passport_telegram_identity_choices_bot_id_telegram_user_id_status_created_at_idx" ON "passport_telegram_identity_choices"("bot_id", "telegram_user_id", "status", "created_at");
CREATE UNIQUE INDEX "passport_telegram_identity_choices_key_deleted_at_key" ON "passport_telegram_identity_choices"("key", "deleted_at");
CREATE TABLE "new_passport_login_challenges" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "challenge_id" TEXT NOT NULL,
    "user_key" TEXT NOT NULL,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "expected_number" INTEGER NOT NULL,
    "status" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_login_challenges" ("bot_id", "challenge_id", "chat_id", "created_at", "created_duid", "deleted_at", "expected_number", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "telegram_user_id", "updated_at", "updated_duid", "user_key") SELECT "bot_id", "challenge_id", "chat_id", "created_at", "created_duid", "deleted_at", "expected_number", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "telegram_user_id", "updated_at", "updated_duid", "user_key" FROM "passport_login_challenges";
DROP TABLE "passport_login_challenges";
ALTER TABLE "new_passport_login_challenges" RENAME TO "passport_login_challenges";
CREATE INDEX "passport_login_challenges_bot_id_telegram_user_id_status_created_at_idx" ON "passport_login_challenges"("bot_id", "telegram_user_id", "status", "created_at");
CREATE INDEX "passport_login_challenges_status_expires_at_idx" ON "passport_login_challenges"("status", "expires_at");
CREATE UNIQUE INDEX "passport_login_challenges_challenge_id_deleted_at_key" ON "passport_login_challenges"("challenge_id", "deleted_at");
CREATE UNIQUE INDEX "passport_login_challenges_key_deleted_at_key" ON "passport_login_challenges"("key", "deleted_at");
CREATE TABLE "new_passport_sso_requests" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "request_id" TEXT NOT NULL,
    "target_site_key" TEXT NOT NULL,
    "target_hostname" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_sso_requests" ("created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "request_id", "status", "target_hostname", "target_site_key", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "request_id", "status", "target_hostname", "target_site_key", "updated_at", "updated_duid" FROM "passport_sso_requests";
DROP TABLE "passport_sso_requests";
ALTER TABLE "new_passport_sso_requests" RENAME TO "passport_sso_requests";
CREATE INDEX "passport_sso_requests_status_expires_at_idx" ON "passport_sso_requests"("status", "expires_at");
CREATE UNIQUE INDEX "passport_sso_requests_request_id_deleted_at_key" ON "passport_sso_requests"("request_id", "deleted_at");
CREATE UNIQUE INDEX "passport_sso_requests_key_deleted_at_key" ON "passport_sso_requests"("key", "deleted_at");
CREATE TABLE "new_passport_login_tickets" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "user_key" TEXT NOT NULL,
    "target_site_key" TEXT NOT NULL,
    "target_hostname" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_login_tickets" ("created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "target_hostname", "target_site_key", "token_hash", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "target_hostname", "target_site_key", "token_hash", "updated_at", "updated_duid", "user_key" FROM "passport_login_tickets";
DROP TABLE "passport_login_tickets";
ALTER TABLE "new_passport_login_tickets" RENAME TO "passport_login_tickets";
CREATE INDEX "passport_login_tickets_status_expires_at_idx" ON "passport_login_tickets"("status", "expires_at");
CREATE UNIQUE INDEX "passport_login_tickets_token_hash_deleted_at_key" ON "passport_login_tickets"("token_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_login_tickets_key_deleted_at_key" ON "passport_login_tickets"("key", "deleted_at");
CREATE TABLE "new_passport_site_sessions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "session_id" TEXT NOT NULL,
    "user_key" TEXT NOT NULL,
    "site_key" TEXT NOT NULL,
    "hostname" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_site_sessions" ("created_at", "created_duid", "deleted_at", "expires_at", "hostname", "id", "key", "owner_bid", "owner_tid", "owner_uid", "session_id", "site_key", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "expires_at", "hostname", "id", "key", "owner_bid", "owner_tid", "owner_uid", "session_id", "site_key", "updated_at", "updated_duid", "user_key" FROM "passport_site_sessions";
DROP TABLE "passport_site_sessions";
ALTER TABLE "new_passport_site_sessions" RENAME TO "passport_site_sessions";
CREATE INDEX "passport_site_sessions_user_key_idx" ON "passport_site_sessions"("user_key");
CREATE INDEX "passport_site_sessions_site_key_hostname_expires_at_idx" ON "passport_site_sessions"("site_key", "hostname", "expires_at");
CREATE UNIQUE INDEX "passport_site_sessions_session_id_deleted_at_key" ON "passport_site_sessions"("session_id", "deleted_at");
CREATE UNIQUE INDEX "passport_site_sessions_key_deleted_at_key" ON "passport_site_sessions"("key", "deleted_at");
CREATE TABLE "new_passport_group_prompts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "chat_id" BIGINT NOT NULL,
    "actor_id" BIGINT NOT NULL,
    "state_json" TEXT NOT NULL DEFAULT '{}',
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_group_prompts" ("actor_id", "chat_id", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "state_json", "updated_at", "updated_duid") SELECT "actor_id", "chat_id", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "state_json", "updated_at", "updated_duid" FROM "passport_group_prompts";
DROP TABLE "passport_group_prompts";
ALTER TABLE "new_passport_group_prompts" RENAME TO "passport_group_prompts";
CREATE INDEX "passport_group_prompts_chat_id_actor_id_updated_at_idx" ON "passport_group_prompts"("chat_id", "actor_id", "updated_at");
CREATE UNIQUE INDEX "passport_group_prompts_key_deleted_at_key" ON "passport_group_prompts"("key", "deleted_at");
CREATE TABLE "new_passport_external_email_otps" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "otp_id" TEXT NOT NULL,
    "pending_identity_hash" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_external_email_otps" ("attempt_count", "code_hash", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "otp_id", "owner_bid", "owner_tid", "owner_uid", "pending_identity_hash", "status", "updated_at", "updated_duid") SELECT "attempt_count", "code_hash", "created_at", "created_duid", "deleted_at", "email", "expires_at", "id", "key", "otp_id", "owner_bid", "owner_tid", "owner_uid", "pending_identity_hash", "status", "updated_at", "updated_duid" FROM "passport_external_email_otps";
DROP TABLE "passport_external_email_otps";
ALTER TABLE "new_passport_external_email_otps" RENAME TO "passport_external_email_otps";
CREATE INDEX "passport_external_email_otps_pending_identity_hash_status_created_at_idx" ON "passport_external_email_otps"("pending_identity_hash", "status", "created_at");
CREATE UNIQUE INDEX "passport_external_email_otps_otp_id_deleted_at_key" ON "passport_external_email_otps"("otp_id", "deleted_at");
CREATE UNIQUE INDEX "passport_external_email_otps_key_deleted_at_key" ON "passport_external_email_otps"("key", "deleted_at");
CREATE TABLE "new_passport_external_identities" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "profile" TEXT NOT NULL DEFAULT '{}'
);
INSERT INTO "new_passport_external_identities" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "profile", "provider", "subject", "updated_at", "updated_duid", "user_key") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "profile", "provider", "subject", "updated_at", "updated_duid", "user_key" FROM "passport_external_identities";
DROP TABLE "passport_external_identities";
ALTER TABLE "new_passport_external_identities" RENAME TO "passport_external_identities";
CREATE INDEX "passport_external_identities_user_key_idx" ON "passport_external_identities"("user_key");
CREATE UNIQUE INDEX "passport_external_identities_provider_subject_deleted_at_key" ON "passport_external_identities"("provider", "subject", "deleted_at");
CREATE UNIQUE INDEX "passport_external_identities_key_deleted_at_key" ON "passport_external_identities"("key", "deleted_at");
CREATE TABLE "new_passport_external_login_states" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "id_hash" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "code_verifier" TEXT NOT NULL,
    "nonce" TEXT NOT NULL,
    "redirect_uri" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "consumed_at" BIGINT,
    "qr_status" TEXT NOT NULL DEFAULT 'pending',
    "qr_user_key" TEXT,
    "oidc_request_id" TEXT
);
INSERT INTO "new_passport_external_login_states" ("code_verifier", "consumed_at", "created_at", "created_duid", "deleted_at", "expires_at", "id", "id_hash", "key", "nonce", "oidc_request_id", "owner_bid", "owner_tid", "owner_uid", "provider", "qr_status", "qr_user_key", "redirect_uri", "updated_at", "updated_duid") SELECT "code_verifier", "consumed_at", "created_at", "created_duid", "deleted_at", "expires_at", "id", "id_hash", "key", "nonce", "oidc_request_id", "owner_bid", "owner_tid", "owner_uid", "provider", "qr_status", "qr_user_key", "redirect_uri", "updated_at", "updated_duid" FROM "passport_external_login_states";
DROP TABLE "passport_external_login_states";
ALTER TABLE "new_passport_external_login_states" RENAME TO "passport_external_login_states";
CREATE INDEX "passport_external_login_states_expires_at_consumed_at_idx" ON "passport_external_login_states"("expires_at", "consumed_at");
CREATE UNIQUE INDEX "passport_external_login_states_id_hash_deleted_at_key" ON "passport_external_login_states"("id_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_external_login_states_key_deleted_at_key" ON "passport_external_login_states"("key", "deleted_at");
CREATE TABLE "new_passport_external_pending_identities" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "id_hash" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "nickname" TEXT NOT NULL,
    "profile" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_external_pending_identities" ("created_at", "created_duid", "deleted_at", "expires_at", "id", "id_hash", "key", "nickname", "owner_bid", "owner_tid", "owner_uid", "profile", "provider", "status", "subject", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "expires_at", "id", "id_hash", "key", "nickname", "owner_bid", "owner_tid", "owner_uid", "profile", "provider", "status", "subject", "updated_at", "updated_duid" FROM "passport_external_pending_identities";
DROP TABLE "passport_external_pending_identities";
ALTER TABLE "new_passport_external_pending_identities" RENAME TO "passport_external_pending_identities";
CREATE UNIQUE INDEX "passport_external_pending_identities_id_hash_deleted_at_key" ON "passport_external_pending_identities"("id_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_external_pending_identities_key_deleted_at_key" ON "passport_external_pending_identities"("key", "deleted_at");
CREATE TABLE "new_passport_external_pending_qr_states" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "pending_identity_hash" TEXT NOT NULL,
    "qr_state_hash" TEXT NOT NULL
);
INSERT INTO "new_passport_external_pending_qr_states" ("created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pending_identity_hash", "qr_state_hash", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "pending_identity_hash", "qr_state_hash", "updated_at", "updated_duid" FROM "passport_external_pending_qr_states";
DROP TABLE "passport_external_pending_qr_states";
ALTER TABLE "new_passport_external_pending_qr_states" RENAME TO "passport_external_pending_qr_states";
CREATE UNIQUE INDEX "passport_external_pending_qr_states_pending_identity_hash_deleted_at_key" ON "passport_external_pending_qr_states"("pending_identity_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_external_pending_qr_states_qr_state_hash_deleted_at_key" ON "passport_external_pending_qr_states"("qr_state_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_external_pending_qr_states_key_deleted_at_key" ON "passport_external_pending_qr_states"("key", "deleted_at");
CREATE TABLE "new_passport_external_providers" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "provider" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "client_secret" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "wechat_mode" TEXT NOT NULL DEFAULT 'open_platform',
    "wechat_redirect_domain" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_passport_external_providers" ("client_id", "client_secret", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider", "status", "title", "updated_at", "updated_duid", "wechat_mode", "wechat_redirect_domain") SELECT "client_id", "client_secret", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "provider", "status", "title", "updated_at", "updated_duid", "wechat_mode", "wechat_redirect_domain" FROM "passport_external_providers";
DROP TABLE "passport_external_providers";
ALTER TABLE "new_passport_external_providers" RENAME TO "passport_external_providers";
CREATE UNIQUE INDEX "passport_external_providers_provider_deleted_at_key" ON "passport_external_providers"("provider", "deleted_at");
CREATE UNIQUE INDEX "passport_external_providers_key_deleted_at_key" ON "passport_external_providers"("key", "deleted_at");
CREATE TABLE "new_passport_oidc_clients" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "client_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "secret_hash" TEXT NOT NULL,
    "redirect_uris" TEXT NOT NULL DEFAULT '[]',
    "allowed_scopes" TEXT NOT NULL DEFAULT 'openid profile email',
    "require_pkce" INTEGER NOT NULL DEFAULT 1,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "backchannel_logout_uri" TEXT NOT NULL DEFAULT '',
    "strict_redirect_uri" INTEGER NOT NULL DEFAULT 0,
    "password_sync" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_passport_oidc_clients" ("allowed_scopes", "backchannel_logout_uri", "client_id", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "password_sync", "redirect_uris", "require_pkce", "secret_hash", "status", "strict_redirect_uri", "title", "updated_at", "updated_duid") SELECT "allowed_scopes", "backchannel_logout_uri", "client_id", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "password_sync", "redirect_uris", "require_pkce", "secret_hash", "status", "strict_redirect_uri", "title", "updated_at", "updated_duid" FROM "passport_oidc_clients";
DROP TABLE "passport_oidc_clients";
ALTER TABLE "new_passport_oidc_clients" RENAME TO "passport_oidc_clients";
CREATE UNIQUE INDEX "passport_oidc_clients_client_id_deleted_at_key" ON "passport_oidc_clients"("client_id", "deleted_at");
CREATE UNIQUE INDEX "passport_oidc_clients_key_deleted_at_key" ON "passport_oidc_clients"("key", "deleted_at");
CREATE TABLE "new_passport_oidc_authorization_requests" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "request_id" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "redirect_uri" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT '',
    "nonce" TEXT NOT NULL DEFAULT '',
    "code_challenge" TEXT NOT NULL DEFAULT '',
    "code_challenge_method" TEXT NOT NULL DEFAULT '',
    "expires_at" BIGINT NOT NULL
);
INSERT INTO "new_passport_oidc_authorization_requests" ("client_id", "code_challenge", "code_challenge_method", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "nonce", "owner_bid", "owner_tid", "owner_uid", "redirect_uri", "request_id", "scope", "state", "updated_at", "updated_duid") SELECT "client_id", "code_challenge", "code_challenge_method", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "nonce", "owner_bid", "owner_tid", "owner_uid", "redirect_uri", "request_id", "scope", "state", "updated_at", "updated_duid" FROM "passport_oidc_authorization_requests";
DROP TABLE "passport_oidc_authorization_requests";
ALTER TABLE "new_passport_oidc_authorization_requests" RENAME TO "passport_oidc_authorization_requests";
CREATE UNIQUE INDEX "passport_oidc_authorization_requests_request_id_deleted_at_key" ON "passport_oidc_authorization_requests"("request_id", "deleted_at");
CREATE UNIQUE INDEX "passport_oidc_authorization_requests_key_deleted_at_key" ON "passport_oidc_authorization_requests"("key", "deleted_at");
CREATE TABLE "new_passport_oidc_authorization_codes" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "code_hash" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "user_key" TEXT NOT NULL,
    "redirect_uri" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "nonce" TEXT NOT NULL DEFAULT '',
    "code_challenge" TEXT NOT NULL DEFAULT '',
    "code_challenge_method" TEXT NOT NULL DEFAULT '',
    "expires_at" BIGINT NOT NULL,
    "consumed_at" BIGINT,
    "session_id" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_passport_oidc_authorization_codes" ("client_id", "code_challenge", "code_challenge_method", "code_hash", "consumed_at", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "nonce", "owner_bid", "owner_tid", "owner_uid", "redirect_uri", "scope", "session_id", "updated_at", "updated_duid", "user_key") SELECT "client_id", "code_challenge", "code_challenge_method", "code_hash", "consumed_at", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "nonce", "owner_bid", "owner_tid", "owner_uid", "redirect_uri", "scope", "session_id", "updated_at", "updated_duid", "user_key" FROM "passport_oidc_authorization_codes";
DROP TABLE "passport_oidc_authorization_codes";
ALTER TABLE "new_passport_oidc_authorization_codes" RENAME TO "passport_oidc_authorization_codes";
CREATE INDEX "passport_oidc_authorization_codes_expires_at_consumed_at_idx" ON "passport_oidc_authorization_codes"("expires_at", "consumed_at");
CREATE UNIQUE INDEX "passport_oidc_authorization_codes_code_hash_deleted_at_key" ON "passport_oidc_authorization_codes"("code_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_oidc_authorization_codes_key_deleted_at_key" ON "passport_oidc_authorization_codes"("key", "deleted_at");
CREATE TABLE "new_passport_oidc_access_tokens" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "user_key" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,
    "session_id" TEXT NOT NULL DEFAULT '',
    "authorization_code_hash" TEXT
);
INSERT INTO "new_passport_oidc_access_tokens" ("authorization_code_hash", "client_id", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "revoked_at", "scope", "session_id", "token_hash", "updated_at", "updated_duid", "user_key") SELECT "authorization_code_hash", "client_id", "created_at", "created_duid", "deleted_at", "expires_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "revoked_at", "scope", "session_id", "token_hash", "updated_at", "updated_duid", "user_key" FROM "passport_oidc_access_tokens";
DROP TABLE "passport_oidc_access_tokens";
ALTER TABLE "new_passport_oidc_access_tokens" RENAME TO "passport_oidc_access_tokens";
CREATE INDEX "passport_oidc_access_tokens_expires_at_revoked_at_idx" ON "passport_oidc_access_tokens"("expires_at", "revoked_at");
CREATE UNIQUE INDEX "passport_oidc_access_tokens_token_hash_deleted_at_key" ON "passport_oidc_access_tokens"("token_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_oidc_access_tokens_authorization_code_hash_deleted_at_key" ON "passport_oidc_access_tokens"("authorization_code_hash", "deleted_at");
CREATE UNIQUE INDEX "passport_oidc_access_tokens_key_deleted_at_key" ON "passport_oidc_access_tokens"("key", "deleted_at");
CREATE TABLE "new_passport_oidc_signing_keys" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "kid" TEXT NOT NULL,
    "private_jwk" TEXT NOT NULL,
    "public_jwk" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active'
);
INSERT INTO "new_passport_oidc_signing_keys" ("created_at", "created_duid", "deleted_at", "id", "key", "kid", "owner_bid", "owner_tid", "owner_uid", "private_jwk", "public_jwk", "status", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "kid", "owner_bid", "owner_tid", "owner_uid", "private_jwk", "public_jwk", "status", "updated_at", "updated_duid" FROM "passport_oidc_signing_keys";
DROP TABLE "passport_oidc_signing_keys";
ALTER TABLE "new_passport_oidc_signing_keys" RENAME TO "passport_oidc_signing_keys";
CREATE UNIQUE INDEX "passport_oidc_signing_keys_kid_deleted_at_key" ON "passport_oidc_signing_keys"("kid", "deleted_at");
CREATE UNIQUE INDEX "passport_oidc_signing_keys_key_deleted_at_key" ON "passport_oidc_signing_keys"("key", "deleted_at");
CREATE TABLE "new_passport_user_profiles" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "pended_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" TEXT NOT NULL,
    "nickname" TEXT,
    "qq" TEXT NOT NULL DEFAULT '',
    "wechat" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_passport_user_profiles" ("created_at", "created_duid", "deleted_at", "id", "key", "nickname", "owner_bid", "owner_tid", "owner_uid", "qq", "updated_at", "updated_duid", "user_key", "wechat") SELECT "created_at", "created_duid", "deleted_at", "id", "key", "nickname", "owner_bid", "owner_tid", "owner_uid", "qq", "updated_at", "updated_duid", "user_key", "wechat" FROM "passport_user_profiles";
DROP TABLE "passport_user_profiles";
ALTER TABLE "new_passport_user_profiles" RENAME TO "passport_user_profiles";
CREATE UNIQUE INDEX "passport_user_profiles_user_key_deleted_at_key" ON "passport_user_profiles"("user_key", "deleted_at");
CREATE UNIQUE INDEX "passport_user_profiles_key_deleted_at_key" ON "passport_user_profiles"("key", "deleted_at");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
