CREATE TABLE IF NOT EXISTS base_users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	created_duid BIGINT,
	updated_duid BIGINT,
	username VARCHAR(255) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	roles TEXT NOT NULL DEFAULT '[]',
	status VARCHAR(32) NOT NULL DEFAULT 'enabled'
);

CREATE TABLE IF NOT EXISTS base_sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	created_duid BIGINT,
	updated_duid BIGINT,
	token_hash VARCHAR(128) NOT NULL UNIQUE,
	user_id BIGINT NOT NULL REFERENCES base_users(id) ON DELETE CASCADE,
	expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS base_sessions_user_id ON base_sessions(user_id);

CREATE TABLE IF NOT EXISTS base_configs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	created_duid BIGINT,
	updated_duid BIGINT,
	"key" VARCHAR(255) NOT NULL UNIQUE,
	value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS base_bootstrap (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	created_duid BIGINT,
	updated_duid BIGINT,
	"key" VARCHAR(255) NOT NULL UNIQUE,
	value TEXT NOT NULL
);
INSERT INTO base_bootstrap (created_at, updated_at, "key", value) VALUES (0, 0, 'initial_admin', 'open') ON CONFLICT ("key") DO NOTHING;

CREATE TABLE IF NOT EXISTS base_oidc_login_requests (
	id VARCHAR(128) PRIMARY KEY,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	created_duid BIGINT,
	updated_duid BIGINT,
	issuer TEXT NOT NULL,
	state VARCHAR(255) NOT NULL UNIQUE,
	nonce VARCHAR(255) NOT NULL,
	code_verifier VARCHAR(255) NOT NULL,
	return_path TEXT NOT NULL DEFAULT '/',
	expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS base_oidc_accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	created_duid BIGINT,
	updated_duid BIGINT,
	issuer VARCHAR(512) NOT NULL,
	subject VARCHAR(512) NOT NULL,
	user_id BIGINT NOT NULL REFERENCES base_users(id) ON DELETE CASCADE,
	profile TEXT NOT NULL DEFAULT '{}',
	UNIQUE (issuer, subject)
);
CREATE INDEX IF NOT EXISTS base_oidc_accounts_user ON base_oidc_accounts(user_id);

CREATE TABLE IF NOT EXISTS base_oidc_sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	created_duid BIGINT,
	updated_duid BIGINT,
	issuer VARCHAR(512) NOT NULL,
	sid VARCHAR(255) NOT NULL,
	session_id BIGINT NOT NULL UNIQUE REFERENCES base_sessions(id) ON DELETE CASCADE,
	UNIQUE (issuer, sid)
);
