-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "BaseUserStatus" AS ENUM ('enabled', 'disabled');

-- CreateEnum
CREATE TYPE "BaseDeviceStatus" AS ENUM ('active', 'revoked');

-- CreateEnum
CREATE TYPE "BaseTenantStatus" AS ENUM ('enabled', 'disabled');

-- CreateEnum
CREATE TYPE "BaseAuditAction" AS ENUM ('insert', 'update', 'soft_delete', 'restore', 'purge');

-- CreateEnum
CREATE TYPE "BaseAuditTransition" AS ENUM ('approve', 'reject', 'withdraw', 'requeue', 'revert', 'redo');

-- CreateEnum
CREATE TYPE "BaseAuditReview" AS ENUM ('none', 'pending', 'approved', 'rejected', 'withdrawn');

-- CreateEnum
CREATE TYPE "BaseAuditDataState" AS ENUM ('unwritten', 'applied', 'reverted');

-- CreateEnum
CREATE TYPE "BaseAuditScope" AS ENUM ('admin', 'self');

-- CreateTable
CREATE TABLE "base_tenants" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" VARCHAR(64) NOT NULL,
    "title" TEXT NOT NULL,
    "status" "BaseTenantStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_branches" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" VARCHAR(64) NOT NULL,
    "title" TEXT NOT NULL,
    "status" "BaseTenantStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_branches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_hosts" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "hostname" TEXT NOT NULL,
    "tenant_id" BIGINT NOT NULL,
    "branch_id" BIGINT NOT NULL,
    "status" "BaseTenantStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_hosts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_users" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "agent_uid" BIGINT,
    "name" TEXT NOT NULL,
    "roles" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "status" "BaseUserStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_sessions" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "device_id" BIGINT NOT NULL,

    CONSTRAINT "base_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_configs" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" VARCHAR(64) NOT NULL,
    "value" TEXT NOT NULL,

    CONSTRAINT "base_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_bootstraps" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" VARCHAR(64) NOT NULL,
    "value" TEXT NOT NULL,

    CONSTRAINT "base_bootstraps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_oidc_login_requests" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "request_id" TEXT NOT NULL,
    "issuer" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "nonce" TEXT NOT NULL,
    "code_verifier" TEXT NOT NULL,
    "return_path" TEXT NOT NULL DEFAULT '/',
    "expires_at" BIGINT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "subject" TEXT NOT NULL DEFAULT '',
    "claims" TEXT NOT NULL DEFAULT '{}',
    "credential" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "base_oidc_login_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_oidc_users" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "issuer" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "profile" TEXT NOT NULL DEFAULT '{}',

    CONSTRAINT "base_oidc_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_oidc_sessions" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "issuer" TEXT NOT NULL,
    "sid" TEXT NOT NULL,
    "session_id" BIGINT NOT NULL,

    CONSTRAINT "base_oidc_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_devices" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_id" BIGINT NOT NULL,
    "fingerprint" JSONB NOT NULL DEFAULT '{}',
    "user_agent" TEXT NOT NULL DEFAULT '',
    "platform" TEXT NOT NULL DEFAULT '',
    "ip_address" TEXT NOT NULL DEFAULT '',
    "network_info" JSONB NOT NULL DEFAULT '{}',
    "status" "BaseDeviceStatus" NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,

    CONSTRAINT "base_devices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_device_users" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "status" "BaseDeviceStatus" NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,

    CONSTRAINT "base_device_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_device_snapshots" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "fingerprint" JSONB NOT NULL DEFAULT '{}',
    "ip_address" TEXT NOT NULL DEFAULT '',
    "network_info" JSONB NOT NULL DEFAULT '{}',
    "user_agent" TEXT NOT NULL DEFAULT '',
    "platform" TEXT NOT NULL DEFAULT '',
    "screen_width" INTEGER NOT NULL DEFAULT 0,
    "screen_height" INTEGER NOT NULL DEFAULT 0,
    "captured_at" BIGINT NOT NULL,

    CONSTRAINT "base_device_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_audit_transitions" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "audit_id" BIGINT NOT NULL,
    "kind" "BaseAuditTransition" NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "base_audit_transitions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_audits" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "operation_id" TEXT NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "scope" "BaseAuditScope" NOT NULL DEFAULT 'admin',
    "request_hostname" TEXT NOT NULL DEFAULT '',
    "request_path" TEXT NOT NULL DEFAULT '',
    "table_name" TEXT NOT NULL,
    "row_id" BIGINT NOT NULL,
    "row_key" VARCHAR(36) NOT NULL DEFAULT '',
    "action" "BaseAuditAction" NOT NULL,
    "changes_before" JSONB NOT NULL DEFAULT '{}',
    "changes_after" JSONB NOT NULL DEFAULT '{}',
    "review_status" "BaseAuditReview" NOT NULL DEFAULT 'none',
    "data_status" "BaseAuditDataState" NOT NULL DEFAULT 'applied',
    "settled_at" BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT "base_audits_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_user_credentials" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_id" BIGINT NOT NULL,
    "password" JSONB NOT NULL,

    CONSTRAINT "base_user_credentials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_user_profiles" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_id" BIGINT NOT NULL,
    "nickname" TEXT,
    "qq" TEXT,
    "wechat" TEXT,
    "email" TEXT,

    CONSTRAINT "base_user_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "base_tenants_key_key" ON "base_tenants"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_tenants_name_deleted_at_key" ON "base_tenants"("name", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_branches_key_key" ON "base_branches"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_branches_owner_tid_name_deleted_at_key" ON "base_branches"("owner_tid", "name", "deleted_at");

-- CreateIndex
CREATE INDEX "base_hosts_tenant_id_idx" ON "base_hosts"("tenant_id");

-- CreateIndex
CREATE INDEX "base_hosts_branch_id_idx" ON "base_hosts"("branch_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_hosts_hostname_key" ON "base_hosts"("hostname");

-- CreateIndex
CREATE UNIQUE INDEX "base_hosts_key_key" ON "base_hosts"("key");

-- CreateIndex
CREATE INDEX "base_users_agent_uid_idx" ON "base_users"("agent_uid");

-- CreateIndex
CREATE UNIQUE INDEX "base_users_owner_tid_name_deleted_at_key" ON "base_users"("owner_tid", "name", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_users_key_key" ON "base_users"("key");

-- CreateIndex
CREATE INDEX "base_sessions_user_id_idx" ON "base_sessions"("user_id");

-- CreateIndex
CREATE INDEX "base_sessions_device_id_idx" ON "base_sessions"("device_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_sessions_token_hash_key" ON "base_sessions"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "base_sessions_key_key" ON "base_sessions"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_configs_key_key" ON "base_configs"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_configs_owner_tid_name_deleted_at_key" ON "base_configs"("owner_tid", "name", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_bootstraps_key_key" ON "base_bootstraps"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_bootstraps_owner_tid_name_deleted_at_key" ON "base_bootstraps"("owner_tid", "name", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_login_requests_request_id_key" ON "base_oidc_login_requests"("request_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_login_requests_state_key" ON "base_oidc_login_requests"("state");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_login_requests_key_key" ON "base_oidc_login_requests"("key");

-- CreateIndex
CREATE INDEX "base_oidc_users_user_id_idx" ON "base_oidc_users"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_users_owner_tid_issuer_subject_key" ON "base_oidc_users"("owner_tid", "issuer", "subject");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_users_key_key" ON "base_oidc_users"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_sessions_session_id_key" ON "base_oidc_sessions"("session_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_sessions_issuer_sid_key" ON "base_oidc_sessions"("issuer", "sid");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_sessions_key_key" ON "base_oidc_sessions"("key");

-- CreateIndex
CREATE INDEX "base_devices_user_id_idx" ON "base_devices"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_devices_key_key" ON "base_devices"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_device_users_device_id_user_id_key" ON "base_device_users"("device_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_device_users_key_key" ON "base_device_users"("key");

-- CreateIndex
CREATE INDEX "base_device_snapshots_device_id_idx" ON "base_device_snapshots"("device_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_device_snapshots_key_key" ON "base_device_snapshots"("key");

-- CreateIndex
CREATE INDEX "base_audit_transitions_audit_id_id_idx" ON "base_audit_transitions"("audit_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "base_audit_transitions_key_key" ON "base_audit_transitions"("key");

-- CreateIndex
CREATE INDEX "base_audits_owner_tid_created_at_idx" ON "base_audits"("owner_tid", "created_at");

-- CreateIndex
CREATE INDEX "base_audits_owner_bid_created_at_idx" ON "base_audits"("owner_bid", "created_at");

-- CreateIndex
CREATE INDEX "base_audits_owner_uid_created_at_idx" ON "base_audits"("owner_uid", "created_at");

-- CreateIndex
CREATE INDEX "base_audits_table_name_row_id_created_at_idx" ON "base_audits"("table_name", "row_id", "created_at");

-- CreateIndex
CREATE INDEX "base_audits_operation_id_idx" ON "base_audits"("operation_id");

-- CreateIndex
CREATE INDEX "base_audits_review_status_created_at_idx" ON "base_audits"("review_status", "created_at");

-- CreateIndex
CREATE INDEX "base_audits_scope_created_at_idx" ON "base_audits"("scope", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_audits_table_name_row_key_settled_at_key" ON "base_audits"("table_name", "row_key", "settled_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_audits_key_key" ON "base_audits"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_user_credentials_user_id_key" ON "base_user_credentials"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_user_credentials_key_key" ON "base_user_credentials"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_user_profiles_user_id_key" ON "base_user_profiles"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "base_user_profiles_owner_tid_nickname_key" ON "base_user_profiles"("owner_tid", "nickname");

-- CreateIndex
CREATE UNIQUE INDEX "base_user_profiles_key_key" ON "base_user_profiles"("key");
