-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "BaseUserStatus" AS ENUM ('enabled', 'disabled');

-- CreateEnum
CREATE TYPE "BaseDeviceStatus" AS ENUM ('active', 'revoked');

-- CreateEnum
CREATE TYPE "BaseTenantStatus" AS ENUM ('enabled', 'disabled');

-- CreateEnum
CREATE TYPE "BaseAuditAction" AS ENUM ('update', 'soft_delete', 'restore');

-- CreateEnum
CREATE TYPE "BaseAuditStatus" AS ENUM ('applied', 'reverted');

-- CreateTable
CREATE TABLE "base_tenants" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" "BaseTenantStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_branches" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" "BaseTenantStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_branches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_hosts" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "hostname" TEXT NOT NULL,
    "tenant_id" BIGINT NOT NULL,
    "branch_id" BIGINT NOT NULL,
    "status" "BaseTenantStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_hosts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_users" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "roles" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "status" "BaseUserStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "base_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_sessions" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "device_id" BIGINT NOT NULL,

    CONSTRAINT "base_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_configs" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,

    CONSTRAINT "base_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_bootstrap" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,

    CONSTRAINT "base_bootstrap_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_oidc_login_requests" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "request_id" TEXT NOT NULL,
    "issuer" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "nonce" TEXT NOT NULL,
    "code_verifier" TEXT NOT NULL,
    "return_path" TEXT NOT NULL DEFAULT '/',
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "base_oidc_login_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_oidc_users" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "issuer" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "profile" TEXT NOT NULL DEFAULT '{}',

    CONSTRAINT "base_oidc_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_oidc_sessions" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "issuer" TEXT NOT NULL,
    "sid" TEXT NOT NULL,
    "session_id" BIGINT NOT NULL,

    CONSTRAINT "base_oidc_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_devices" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_id" BIGINT NOT NULL,
    "key" TEXT NOT NULL,
    "fingerprint" JSONB NOT NULL DEFAULT '{}',
    "user_agent" TEXT NOT NULL DEFAULT '',
    "platform" TEXT NOT NULL DEFAULT '',
    "ip_address" TEXT NOT NULL DEFAULT '',
    "network_info" JSONB NOT NULL DEFAULT '{}',
    "status" "BaseDeviceStatus" NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,

    CONSTRAINT "base_devices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_device_users" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "status" "BaseDeviceStatus" NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,

    CONSTRAINT "base_device_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_device_snapshots" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "fingerprint" JSONB NOT NULL DEFAULT '{}',
    "ip_address" TEXT NOT NULL DEFAULT '',
    "network_info" JSONB NOT NULL DEFAULT '{}',
    "user_agent" TEXT NOT NULL DEFAULT '',
    "platform" TEXT NOT NULL DEFAULT '',
    "screen_width" INTEGER NOT NULL DEFAULT 0,
    "screen_height" INTEGER NOT NULL DEFAULT 0,
    "captured_at" BIGINT NOT NULL,

    CONSTRAINT "base_device_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "base_audit_entries" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "operation_id" TEXT NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "table_name" TEXT NOT NULL,
    "row_id" BIGINT NOT NULL,
    "action" "BaseAuditAction" NOT NULL,
    "changes" JSONB NOT NULL DEFAULT '{}',
    "status" "BaseAuditStatus" NOT NULL DEFAULT 'applied',

    CONSTRAINT "base_audit_entries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "base_tenants_key_deleted_at_key" ON "base_tenants"("key", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_branches_key_owner_tid_deleted_at_key" ON "base_branches"("key", "owner_tid", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_hosts_hostname_deleted_at_key" ON "base_hosts"("hostname", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_users_name_owner_tid_deleted_at_key" ON "base_users"("name", "owner_tid", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_sessions_token_hash_deleted_at_key" ON "base_sessions"("token_hash", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_configs_key_owner_tid_deleted_at_key" ON "base_configs"("key", "owner_tid", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_bootstrap_key_owner_tid_deleted_at_key" ON "base_bootstrap"("key", "owner_tid", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_login_requests_request_id_deleted_at_key" ON "base_oidc_login_requests"("request_id", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_login_requests_state_deleted_at_key" ON "base_oidc_login_requests"("state", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_users_issuer_subject_owner_tid_deleted_at_key" ON "base_oidc_users"("issuer", "subject", "owner_tid", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_sessions_session_id_deleted_at_key" ON "base_oidc_sessions"("session_id", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_sessions_issuer_sid_deleted_at_key" ON "base_oidc_sessions"("issuer", "sid", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_devices_key_deleted_at_key" ON "base_devices"("key", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "base_device_users_device_id_user_id_deleted_at_key" ON "base_device_users"("device_id", "user_id", "deleted_at");

-- CreateIndex
CREATE INDEX "base_audit_entries_owner_tid_created_at_idx" ON "base_audit_entries"("owner_tid", "created_at");

-- CreateIndex
CREATE INDEX "base_audit_entries_owner_bid_created_at_idx" ON "base_audit_entries"("owner_bid", "created_at");

-- CreateIndex
CREATE INDEX "base_audit_entries_owner_uid_created_at_idx" ON "base_audit_entries"("owner_uid", "created_at");

-- CreateIndex
CREATE INDEX "base_audit_entries_table_name_row_id_created_at_idx" ON "base_audit_entries"("table_name", "row_id", "created_at");

-- CreateIndex
CREATE INDEX "base_audit_entries_operation_id_idx" ON "base_audit_entries"("operation_id");
