-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateEnum
CREATE TYPE "BaseAuditApproval" AS ENUM ('approve', 'reject', 'withdraw', 'requeue', 'revert', 'redo');

-- DropTable
DROP TABLE "base_audit_transitions";

-- DropEnum
DROP TYPE "BaseAuditTransition";

-- CreateTable
CREATE TABLE "base_audit_approvals" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "audit_id" BIGINT NOT NULL,
    "kind" "BaseAuditApproval" NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "base_audit_approvals_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "base_audit_approvals_audit_id_id_idx" ON "base_audit_approvals"("audit_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "base_audit_approvals_key_key" ON "base_audit_approvals"("key");
