-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "base_tenants_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_branches_owner_tid_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_hosts_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_users_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_sessions_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_configs_owner_tid_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_bootstrap_owner_tid_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_oidc_login_requests_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_oidc_users_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_oidc_sessions_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_devices_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_device_users_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_device_snapshots_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_approval_events_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_approvals_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_user_credentials_key_deleted_at_key";

-- DropIndex
DROP INDEX "base_user_profiles_key_deleted_at_key";

-- CreateIndex
CREATE UNIQUE INDEX "base_tenants_key_key" ON "base_tenants"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_branches_owner_tid_key_key" ON "base_branches"("owner_tid", "key");

-- CreateIndex
CREATE UNIQUE INDEX "base_hosts_key_key" ON "base_hosts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_users_key_key" ON "base_users"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_sessions_key_key" ON "base_sessions"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_configs_owner_tid_key_key" ON "base_configs"("owner_tid", "key");

-- CreateIndex
CREATE UNIQUE INDEX "base_bootstrap_owner_tid_key_key" ON "base_bootstrap"("owner_tid", "key");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_login_requests_key_key" ON "base_oidc_login_requests"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_users_key_key" ON "base_oidc_users"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_oidc_sessions_key_key" ON "base_oidc_sessions"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_devices_key_key" ON "base_devices"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_device_users_key_key" ON "base_device_users"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_device_snapshots_key_key" ON "base_device_snapshots"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_approval_events_key_key" ON "base_approval_events"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_approvals_key_key" ON "base_approvals"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_user_credentials_key_key" ON "base_user_credentials"("key");

-- CreateIndex
CREATE UNIQUE INDEX "base_user_profiles_key_key" ON "base_user_profiles"("key");
