-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE "base_audit_entries" ADD COLUMN     "withdrawn_at" BIGINT,
ADD COLUMN     "withdrawn_duid" BIGINT;
