-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE "base_approvals" ADD COLUMN     "settled_at" BIGINT NOT NULL DEFAULT 0;

-- CreateIndex
CREATE UNIQUE INDEX "base_approvals_table_name_row_key_settled_at_key" ON "base_approvals"("table_name", "row_key", "settled_at");
