-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateEnum
CREATE TYPE "BaseApprovalAction" AS ENUM ('update', 'soft_delete', 'restore');

-- CreateEnum
CREATE TYPE "BaseApprovalStatus" AS ENUM ('pending', 'applied', 'rejected', 'withdrawn', 'reverted');

-- DropTable
DROP TABLE "base_audit_entries";

-- DropEnum
DROP TYPE "BaseAuditAction";

-- DropEnum
DROP TYPE "BaseAuditStatus";

-- CreateTable
CREATE TABLE "base_approvals" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "operation_id" TEXT NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "request_hostname" TEXT NOT NULL DEFAULT '',
    "request_path" TEXT NOT NULL DEFAULT '',
    "table_name" TEXT NOT NULL,
    "row_id" BIGINT NOT NULL,
    "action" "BaseApprovalAction" NOT NULL,
    "changes" JSONB NOT NULL DEFAULT '{}',
    "status" "BaseApprovalStatus" NOT NULL DEFAULT 'applied',
    "reviewed_at" BIGINT,
    "reviewed_duid" BIGINT,
    "review_reason" TEXT NOT NULL DEFAULT '',
    "withdrawn_at" BIGINT,
    "withdrawn_duid" BIGINT,
    "reverted_at" BIGINT,
    "reverted_duid" BIGINT,
    "revert_reason" TEXT NOT NULL DEFAULT '',
    "restored_at" BIGINT,
    "restored_duid" BIGINT,
    "restore_reason" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "base_approvals_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "base_approvals_owner_tid_created_at_idx" ON "base_approvals"("owner_tid", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_owner_bid_created_at_idx" ON "base_approvals"("owner_bid", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_owner_uid_created_at_idx" ON "base_approvals"("owner_uid", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_table_name_row_id_created_at_idx" ON "base_approvals"("table_name", "row_id", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_operation_id_idx" ON "base_approvals"("operation_id");

-- CreateIndex
CREATE INDEX "base_approvals_status_created_at_idx" ON "base_approvals"("status", "created_at");
