-- Generated by Prisma migrate diff. Source: prisma/base.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "base_approvals_status_created_at_idx";

-- AlterTable
ALTER TABLE "base_approvals" DROP COLUMN "status";

-- DropEnum
DROP TYPE "BaseApprovalStatus";

-- CreateIndex
CREATE INDEX "base_approvals_review_status_created_at_idx" ON "base_approvals"("review_status", "created_at");
