-- Generated by Prisma migrate diff. Source: prisma/global.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE "global_sites" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "base_site_key" TEXT,
    "dsn" TEXT NOT NULL DEFAULT '',
    "dsn_password" TEXT,
    "database_binding" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "migration_status" TEXT NOT NULL DEFAULT 'ready',
    "is_default" INTEGER NOT NULL DEFAULT 0,
    "is_system" INTEGER NOT NULL DEFAULT 0,
    "passport_sso_enabled" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "global_site_hosts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "hostname" TEXT NOT NULL,
    "site_key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_credentials" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "account_id" TEXT NOT NULL DEFAULT '',
    "access_key_id" TEXT NOT NULL DEFAULT '',
    "access_key_secret" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_object_storage_buckets" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "cloud_credential_id" BIGINT NOT NULL,
    "endpoint" TEXT NOT NULL,
    "region" TEXT NOT NULL DEFAULT '',
    "bucket" TEXT NOT NULL,
    "path_style" INTEGER NOT NULL DEFAULT 0,
    "public_base_url" TEXT NOT NULL DEFAULT '',
    "extra_config" TEXT NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_object_storage_bindings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "site_key" TEXT NOT NULL,
    "bucket_id" BIGINT NOT NULL,
    "key_prefix" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_object_storage_binding_purposes" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "binding_id" BIGINT NOT NULL,
    "site_key" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "is_default" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "global_telegram_bots" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "secret_token" TEXT NOT NULL,
    "webhook_hostname" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_email_channels" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "cloud_credential_id" BIGINT NOT NULL,
    "region" TEXT NOT NULL,
    "account_name" TEXT NOT NULL,
    "from_alias" TEXT NOT NULL,
    "reply_to_address" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_email_templates" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "type" TEXT NOT NULL DEFAULT 'email_verification',
    "title" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "body_html" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_email_bindings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "site_key" TEXT NOT NULL,
    "channel_id" BIGINT NOT NULL,
    "template_id" BIGINT NOT NULL,
    "purpose" TEXT NOT NULL,
    "is_default" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);

-- CreateTable
CREATE TABLE "global_cloud_email_template_publications" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "template_id" BIGINT NOT NULL,
    "cloud_credential_id" BIGINT NOT NULL,
    "region" TEXT NOT NULL,
    "provider_template_id" TEXT NOT NULL,
    "content_hash" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "global_snowflake_states" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "worker_id" INTEGER NOT NULL,
    "last_at" BIGINT NOT NULL
);

-- CreateIndex
CREATE INDEX "global_sites_base_site_key_idx" ON "global_sites"("base_site_key");

-- CreateIndex
CREATE UNIQUE INDEX "global_sites_key_key" ON "global_sites"("key");

-- CreateIndex
CREATE INDEX "global_site_hosts_site_key_idx" ON "global_site_hosts"("site_key");

-- CreateIndex
CREATE UNIQUE INDEX "global_site_hosts_hostname_key" ON "global_site_hosts"("hostname");

-- CreateIndex
CREATE UNIQUE INDEX "global_site_hosts_key_key" ON "global_site_hosts"("key");

-- CreateIndex
CREATE INDEX "global_cloud_credentials_account_id_idx" ON "global_cloud_credentials"("account_id");

-- CreateIndex
CREATE INDEX "global_cloud_credentials_access_key_id_idx" ON "global_cloud_credentials"("access_key_id");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_credentials_title_key" ON "global_cloud_credentials"("title");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_credentials_key_key" ON "global_cloud_credentials"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_buckets_cloud_credential_id_endpoint_bucket_key" ON "global_cloud_object_storage_buckets"("cloud_credential_id", "endpoint", "bucket");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_buckets_key_key" ON "global_cloud_object_storage_buckets"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_id_site_key_key" ON "global_cloud_object_storage_bindings"("id", "site_key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_site_key_bucket_id_key_prefix_key" ON "global_cloud_object_storage_bindings"("site_key", "bucket_id", "key_prefix");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_key_key" ON "global_cloud_object_storage_bindings"("key");

-- CreateIndex
CREATE INDEX "global_cloud_object_storage_binding_purposes_site_key_idx" ON "global_cloud_object_storage_binding_purposes"("site_key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_binding_purposes_binding_id_purpose_key" ON "global_cloud_object_storage_binding_purposes"("binding_id", "purpose");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_binding_purposes_key_key" ON "global_cloud_object_storage_binding_purposes"("key");

-- CreateIndex
CREATE INDEX "global_telegram_bots_webhook_hostname_idx" ON "global_telegram_bots"("webhook_hostname");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_title_key" ON "global_telegram_bots"("title");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_token_key" ON "global_telegram_bots"("token");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_username_key" ON "global_telegram_bots"("username");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_key_key" ON "global_telegram_bots"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_channels_cloud_credential_id_region_account_name_key" ON "global_cloud_email_channels"("cloud_credential_id", "region", "account_name");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_channels_key_key" ON "global_cloud_email_channels"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_templates_key_key" ON "global_cloud_email_templates"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_bindings_site_key_channel_id_template_id_purpose_key" ON "global_cloud_email_bindings"("site_key", "channel_id", "template_id", "purpose");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_bindings_key_key" ON "global_cloud_email_bindings"("key");

-- CreateIndex
CREATE INDEX "global_cloud_email_template_publications_provider_template_id_idx" ON "global_cloud_email_template_publications"("provider_template_id");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_template_publications_template_id_cloud_credential_id_region_key" ON "global_cloud_email_template_publications"("template_id", "cloud_credential_id", "region");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_template_publications_key_key" ON "global_cloud_email_template_publications"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_snowflake_states_worker_id_key" ON "global_snowflake_states"("worker_id");
