-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE "pve_regions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "sort_order" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "pve_nodes" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "region_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "port" INTEGER NOT NULL DEFAULT 8006,
    "cluster_name" TEXT NOT NULL DEFAULT '',
    "api_user" TEXT NOT NULL,
    "api_token_id" TEXT NOT NULL,
    "api_token_secret" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "last_checked_at" INTEGER,
    "last_error" TEXT NOT NULL DEFAULT ''
);

-- CreateTable
CREATE TABLE "pve_instance_flavors" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "instance_flavor_code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "cpu_cores" INTEGER NOT NULL,
    "memory_gb" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "sort_order" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "pve_vms" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "kind" TEXT NOT NULL DEFAULT 'qemu',
    "region_id" BIGINT NOT NULL,
    "node_id" BIGINT NOT NULL,
    "instance_flavor_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'allocating',
    "pve_status" TEXT NOT NULL DEFAULT '',
    "pve_config" TEXT NOT NULL DEFAULT '{}',
    "error_message" TEXT NOT NULL DEFAULT ''
);

-- CreateTable
CREATE TABLE "pve_vm_tasks" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "vm_id" BIGINT NOT NULL,
    "action" TEXT NOT NULL,
    "idempotency_key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "request_payload" TEXT NOT NULL DEFAULT '{}',
    "response_payload" TEXT NOT NULL DEFAULT '{}',
    "retry_count" INTEGER NOT NULL DEFAULT 0,
    "error_message" TEXT NOT NULL DEFAULT ''
);

-- CreateIndex
CREATE UNIQUE INDEX "pve_regions_code_deleted_at_key" ON "pve_regions"("code", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "pve_instance_flavors_cpu_cores_memory_gb_deleted_at_key" ON "pve_instance_flavors"("cpu_cores", "memory_gb", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "pve_vm_tasks_idempotency_key_deleted_at_key" ON "pve_vm_tasks"("idempotency_key", "deleted_at");
