-- Generated by Prisma migrate diff. Source: prisma/seed.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

INSERT INTO global_sites (key, name, base_site_key, dsn, database_binding, status, migration_status, is_default, is_system) VALUES ('global', '全局控制面', 'base', '', '', 'enabled', 'ready', 1, 1) ON CONFLICT(key, deleted_at) DO NOTHING;
INSERT INTO base_tenants (created_at, updated_at, key, name, status) VALUES (0, 0, 'default', '默认租户', 'enabled') ON CONFLICT(key, deleted_at) DO NOTHING;
INSERT INTO base_branches (created_at, updated_at, key, name, status) VALUES (0, 0, 'main', '主分站', 'enabled') ON CONFLICT(key, owner_tid, deleted_at) DO NOTHING;
INSERT INTO base_bootstrap (created_at, updated_at, key, value) VALUES (0, 0, 'initial_admin', 'open') ON CONFLICT(key, owner_tid, deleted_at) DO NOTHING;
