-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE "sms_integration_clients" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "binding_scope" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "last_used_at" BIGINT
);

-- CreateTable
CREATE TABLE "sms_integration_client_keys" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "integration_client_id" BIGINT NOT NULL,
    "kid" TEXT NOT NULL,
    "public_key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "retired_at" BIGINT
);

-- CreateTable
CREATE TABLE "sms_phones" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "number" TEXT NOT NULL,
    "title" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "bound_at" BIGINT NOT NULL DEFAULT 0,
    "revoked_at" BIGINT
);

-- CreateTable
CREATE TABLE "sms_shortcut_tokens" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_sha256" TEXT NOT NULL,
    "phone_id" BIGINT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "idempotency_token" TEXT NOT NULL,
    "last_used_at" BIGINT
);

-- CreateTable
CREATE TABLE "sms_shortcut_artifacts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_id" BIGINT NOT NULL,
    "object_key" TEXT NOT NULL,
    "file_sha256" TEXT NOT NULL,
    "size_bytes" BIGINT NOT NULL DEFAULT 0,
    "content_type" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "generator_machine_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ready'
);

-- CreateTable
CREATE TABLE "sms_messages" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "phone_id" BIGINT NOT NULL,
    "content" TEXT NOT NULL,
    "recipients" TEXT NOT NULL DEFAULT '',
    "sender" TEXT NOT NULL DEFAULT '',
    "received_at" BIGINT NOT NULL DEFAULT 0,
    "payload_hash" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "sms_ticket_nonces" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "integration_client_id" BIGINT NOT NULL,
    "nonce" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "sms_access_keys" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "secret_hash" TEXT NOT NULL,
    "secret_prefix" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "expires_at" BIGINT,
    "revoked_at" BIGINT
);

-- CreateTable
CREATE TABLE "sms_push_endpoints" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "url" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "phone_id" BIGINT,
    "last_success_at" BIGINT,
    "last_error" TEXT NOT NULL DEFAULT ''
);

-- CreateTable
CREATE TABLE "sms_push_deliveries" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "message_id" BIGINT NOT NULL,
    "push_endpoint_id" BIGINT NOT NULL,
    "delivery_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "next_attempt_at" BIGINT NOT NULL DEFAULT 0,
    "last_error" TEXT NOT NULL DEFAULT ''
);

-- CreateTable
CREATE TABLE "sms_generator_machines" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "secret_hash" TEXT NOT NULL,
    "secret_prefix" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "last_used_at" BIGINT
);

-- CreateIndex
CREATE UNIQUE INDEX "sms_integration_clients_key_key" ON "sms_integration_clients"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_integration_clients_owner_tid_name_deleted_at_key" ON "sms_integration_clients"("owner_tid", "name", "deleted_at");

-- CreateIndex
CREATE INDEX "sms_integration_client_keys_integration_client_id_idx" ON "sms_integration_client_keys"("integration_client_id");

-- CreateIndex
CREATE UNIQUE INDEX "sms_integration_client_keys_key_key" ON "sms_integration_client_keys"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_integration_client_keys_integration_client_id_kid_key" ON "sms_integration_client_keys"("integration_client_id", "kid");

-- CreateIndex
CREATE UNIQUE INDEX "sms_phones_key_key" ON "sms_phones"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_phones_owner_tid_number_deleted_at_key" ON "sms_phones"("owner_tid", "number", "deleted_at");

-- CreateIndex
CREATE INDEX "sms_shortcut_tokens_phone_id_idx" ON "sms_shortcut_tokens"("phone_id");

-- CreateIndex
CREATE UNIQUE INDEX "sms_shortcut_tokens_key_key" ON "sms_shortcut_tokens"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_shortcut_tokens_token_sha256_key" ON "sms_shortcut_tokens"("token_sha256");

-- CreateIndex
CREATE UNIQUE INDEX "sms_shortcut_tokens_idempotency_token_key" ON "sms_shortcut_tokens"("idempotency_token");

-- CreateIndex
CREATE INDEX "sms_shortcut_artifacts_token_id_idx" ON "sms_shortcut_artifacts"("token_id");

-- CreateIndex
CREATE INDEX "sms_shortcut_artifacts_generator_machine_id_idx" ON "sms_shortcut_artifacts"("generator_machine_id");

-- CreateIndex
CREATE UNIQUE INDEX "sms_shortcut_artifacts_key_key" ON "sms_shortcut_artifacts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_shortcut_artifacts_object_key_key" ON "sms_shortcut_artifacts"("object_key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_shortcut_artifacts_token_id_version_key" ON "sms_shortcut_artifacts"("token_id", "version");

-- CreateIndex
CREATE INDEX "sms_messages_phone_id_idx" ON "sms_messages"("phone_id");

-- CreateIndex
CREATE INDEX "sms_messages_received_at_idx" ON "sms_messages"("received_at");

-- CreateIndex
CREATE UNIQUE INDEX "sms_messages_key_key" ON "sms_messages"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_messages_phone_id_payload_hash_key" ON "sms_messages"("phone_id", "payload_hash");

-- CreateIndex
CREATE INDEX "sms_ticket_nonces_integration_client_id_idx" ON "sms_ticket_nonces"("integration_client_id");

-- CreateIndex
CREATE INDEX "sms_ticket_nonces_expires_at_idx" ON "sms_ticket_nonces"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "sms_ticket_nonces_key_key" ON "sms_ticket_nonces"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_ticket_nonces_integration_client_id_nonce_key" ON "sms_ticket_nonces"("integration_client_id", "nonce");

-- CreateIndex
CREATE UNIQUE INDEX "sms_access_keys_key_key" ON "sms_access_keys"("key");

-- CreateIndex
CREATE INDEX "sms_push_endpoints_phone_id_idx" ON "sms_push_endpoints"("phone_id");

-- CreateIndex
CREATE UNIQUE INDEX "sms_push_endpoints_key_key" ON "sms_push_endpoints"("key");

-- CreateIndex
CREATE INDEX "sms_push_deliveries_message_id_idx" ON "sms_push_deliveries"("message_id");

-- CreateIndex
CREATE INDEX "sms_push_deliveries_push_endpoint_id_idx" ON "sms_push_deliveries"("push_endpoint_id");

-- CreateIndex
CREATE INDEX "sms_push_deliveries_next_attempt_at_idx" ON "sms_push_deliveries"("next_attempt_at");

-- CreateIndex
CREATE UNIQUE INDEX "sms_push_deliveries_key_key" ON "sms_push_deliveries"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_push_deliveries_delivery_id_key" ON "sms_push_deliveries"("delivery_id");

-- CreateIndex
CREATE UNIQUE INDEX "sms_push_deliveries_message_id_push_endpoint_id_key" ON "sms_push_deliveries"("message_id", "push_endpoint_id");

-- CreateIndex
CREATE UNIQUE INDEX "sms_generator_machines_key_key" ON "sms_generator_machines"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_generator_machines_owner_tid_name_deleted_at_key" ON "sms_generator_machines"("owner_tid", "name", "deleted_at");
