-- Generated by Prisma migrate diff. Source: prisma/base.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropTable
PRAGMA foreign_keys=off;
DROP TABLE "base_audit_entries";
PRAGMA foreign_keys=on;

-- CreateTable
CREATE TABLE "base_approvals" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "operation_id" TEXT NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "request_hostname" TEXT NOT NULL DEFAULT '',
    "request_path" TEXT NOT NULL DEFAULT '',
    "table_name" TEXT NOT NULL,
    "row_id" BIGINT NOT NULL,
    "action" TEXT NOT NULL,
    "changes" TEXT NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'applied',
    "reviewed_at" BIGINT,
    "reviewed_duid" BIGINT,
    "review_reason" TEXT NOT NULL DEFAULT '',
    "withdrawn_at" BIGINT,
    "withdrawn_duid" BIGINT,
    "reverted_at" BIGINT,
    "reverted_duid" BIGINT,
    "revert_reason" TEXT NOT NULL DEFAULT '',
    "restored_at" BIGINT,
    "restored_duid" BIGINT,
    "restore_reason" TEXT NOT NULL DEFAULT ''
);

-- CreateIndex
CREATE INDEX "base_approvals_owner_tid_created_at_idx" ON "base_approvals"("owner_tid", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_owner_bid_created_at_idx" ON "base_approvals"("owner_bid", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_owner_uid_created_at_idx" ON "base_approvals"("owner_uid", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_table_name_row_id_created_at_idx" ON "base_approvals"("table_name", "row_id", "created_at");

-- CreateIndex
CREATE INDEX "base_approvals_operation_id_idx" ON "base_approvals"("operation_id");

-- CreateIndex
CREATE INDEX "base_approvals_status_created_at_idx" ON "base_approvals"("status", "created_at");
