-- Generated by Prisma migrate diff. Source: prisma/global.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_global_site_hosts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "hostname" TEXT NOT NULL,
    "site_key" TEXT NOT NULL,
    "client_key" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_site_hosts" ("created_at", "created_duid", "deleted_at", "hostname", "id", "key", "owner_bid", "owner_tid", "owner_uid", "queued_at", "site_key", "status", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "hostname", "id", "key", "owner_bid", "owner_tid", "owner_uid", "queued_at", "site_key", "status", "updated_at", "updated_duid" FROM "global_site_hosts";
DROP TABLE "global_site_hosts";
ALTER TABLE "new_global_site_hosts" RENAME TO "global_site_hosts";
CREATE INDEX "global_site_hosts_site_key_idx" ON "global_site_hosts"("site_key");
CREATE UNIQUE INDEX "global_site_hosts_hostname_key" ON "global_site_hosts"("hostname");
CREATE UNIQUE INDEX "global_site_hosts_key_key" ON "global_site_hosts"("key");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
