-- Generated by Prisma migrate diff. Source: prisma/global.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_global_sites" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "base_site_key" TEXT,
    "dsn" TEXT NOT NULL DEFAULT '',
    "dsn_password" TEXT,
    "database_binding" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "migration_status" TEXT NOT NULL DEFAULT 'ready',
    "is_default" INTEGER NOT NULL DEFAULT 0,
    "is_system" INTEGER NOT NULL DEFAULT 0,
    "passport_sso_enabled" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_global_sites" ("base_site_key", "created_at", "created_duid", "database_binding", "deleted_at", "dsn", "dsn_password", "id", "is_default", "is_system", "key", "migration_status", "owner_bid", "owner_tid", "owner_uid", "passport_sso_enabled", "status", "updated_at", "updated_duid") SELECT "base_site_key", "created_at", "created_duid", "database_binding", "deleted_at", "dsn", "dsn_password", "id", "is_default", "is_system", "key", "migration_status", "owner_bid", "owner_tid", "owner_uid", "passport_sso_enabled", "status", "updated_at", "updated_duid" FROM "global_sites";
DROP TABLE "global_sites";
ALTER TABLE "new_global_sites" RENAME TO "global_sites";
CREATE UNIQUE INDEX "global_sites_key_deleted_at_key" ON "global_sites"("key", "deleted_at");
CREATE TABLE "new_global_cloud_credentials" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "account_id" TEXT NOT NULL DEFAULT '',
    "access_key_id" TEXT NOT NULL DEFAULT '',
    "access_key_secret" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_credentials" ("access_key_id", "access_key_secret", "account_id", "created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "provider", "status", "updated_at", "updated_duid") SELECT "access_key_id", "access_key_secret", "account_id", "created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "provider", "status", "updated_at", "updated_duid" FROM "global_cloud_credentials";
DROP TABLE "global_cloud_credentials";
ALTER TABLE "new_global_cloud_credentials" RENAME TO "global_cloud_credentials";
CREATE UNIQUE INDEX "global_cloud_credentials_title_deleted_at_key" ON "global_cloud_credentials"("title", "deleted_at");
CREATE TABLE "new_global_telegram_bots" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "secret_token" TEXT NOT NULL,
    "webhook_hostname" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_telegram_bots" ("created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "secret_token", "status", "token", "updated_at", "updated_duid", "username", "webhook_hostname") SELECT "created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "secret_token", "status", "token", "updated_at", "updated_duid", "username", "webhook_hostname" FROM "global_telegram_bots";
DROP TABLE "global_telegram_bots";
ALTER TABLE "new_global_telegram_bots" RENAME TO "global_telegram_bots";
CREATE INDEX "global_telegram_bots_webhook_hostname_idx" ON "global_telegram_bots"("webhook_hostname");
CREATE UNIQUE INDEX "global_telegram_bots_title_deleted_at_key" ON "global_telegram_bots"("title", "deleted_at");
CREATE UNIQUE INDEX "global_telegram_bots_token_deleted_at_key" ON "global_telegram_bots"("token", "deleted_at");
CREATE UNIQUE INDEX "global_telegram_bots_username_deleted_at_key" ON "global_telegram_bots"("username", "deleted_at");
CREATE TABLE "new_global_cloud_email_templates" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'email_verification',
    "title" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "body_html" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_global_cloud_email_templates" ("body_html", "body_text", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "subject", "type", "updated_at", "updated_duid") SELECT "body_html", "body_text", "created_at", "created_duid", "deleted_at", "id", "key", "owner_bid", "owner_tid", "owner_uid", "status", "subject", "type", "updated_at", "updated_duid" FROM "global_cloud_email_templates";
DROP TABLE "global_cloud_email_templates";
ALTER TABLE "new_global_cloud_email_templates" RENAME TO "global_cloud_email_templates";
CREATE UNIQUE INDEX "global_cloud_email_templates_key_deleted_at_key" ON "global_cloud_email_templates"("key", "deleted_at");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
