-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_pve_regions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "sort_order" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_pve_regions" ("created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "sort_order", "status", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "sort_order", "status", "updated_at", "updated_duid" FROM "pve_regions";
DROP TABLE "pve_regions";
ALTER TABLE "new_pve_regions" RENAME TO "pve_regions";
CREATE UNIQUE INDEX "pve_regions_key_deleted_at_key" ON "pve_regions"("key", "deleted_at");
CREATE TABLE "new_pve_instance_flavors" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "cpu_cores" INTEGER NOT NULL,
    "memory_gb" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "sort_order" INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "new_pve_instance_flavors" ("cpu_cores", "created_at", "created_duid", "deleted_at", "id", "memory_gb", "owner_bid", "owner_tid", "owner_uid", "sort_order", "status", "updated_at", "updated_duid") SELECT "cpu_cores", "created_at", "created_duid", "deleted_at", "id", "memory_gb", "owner_bid", "owner_tid", "owner_uid", "sort_order", "status", "updated_at", "updated_duid" FROM "pve_instance_flavors";
DROP TABLE "pve_instance_flavors";
ALTER TABLE "new_pve_instance_flavors" RENAME TO "pve_instance_flavors";
CREATE UNIQUE INDEX "pve_instance_flavors_key_deleted_at_key" ON "pve_instance_flavors"("key", "deleted_at");
CREATE UNIQUE INDEX "pve_instance_flavors_cpu_cores_memory_gb_deleted_at_key" ON "pve_instance_flavors"("cpu_cores", "memory_gb", "deleted_at");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
