-- Generated by Prisma migrate diff. Source: prisma/base.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_base_hosts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "hostname" TEXT NOT NULL,
    "tenant_id" BIGINT NOT NULL,
    "branch_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_base_hosts" ("branch_id", "created_at", "created_duid", "deleted_at", "hostname", "id", "owner_bid", "owner_tid", "owner_uid", "status", "tenant_id", "updated_at", "updated_duid") SELECT "branch_id", "created_at", "created_duid", "deleted_at", "hostname", "id", "owner_bid", "owner_tid", "owner_uid", "status", "tenant_id", "updated_at", "updated_duid" FROM "base_hosts";
DROP TABLE "base_hosts";
ALTER TABLE "new_base_hosts" RENAME TO "base_hosts";
CREATE UNIQUE INDEX "base_hosts_hostname_deleted_at_key" ON "base_hosts"("hostname", "deleted_at");
CREATE UNIQUE INDEX "base_hosts_key_deleted_at_key" ON "base_hosts"("key", "deleted_at");
CREATE TABLE "new_base_users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "roles" TEXT NOT NULL DEFAULT '[]',
    "status" TEXT NOT NULL DEFAULT 'enabled'
);
INSERT INTO "new_base_users" ("created_at", "created_duid", "deleted_at", "id", "name", "owner_bid", "owner_tid", "owner_uid", "roles", "status", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "name", "owner_bid", "owner_tid", "owner_uid", "roles", "status", "updated_at", "updated_duid" FROM "base_users";
DROP TABLE "base_users";
ALTER TABLE "new_base_users" RENAME TO "base_users";
CREATE UNIQUE INDEX "base_users_owner_tid_name_deleted_at_key" ON "base_users"("owner_tid", "name", "deleted_at");
CREATE UNIQUE INDEX "base_users_key_deleted_at_key" ON "base_users"("key", "deleted_at");
CREATE TABLE "new_base_sessions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "device_id" BIGINT NOT NULL
);
INSERT INTO "new_base_sessions" ("created_at", "created_duid", "deleted_at", "device_id", "expires_at", "id", "owner_bid", "owner_tid", "owner_uid", "token_hash", "updated_at", "updated_duid", "user_id") SELECT "created_at", "created_duid", "deleted_at", "device_id", "expires_at", "id", "owner_bid", "owner_tid", "owner_uid", "token_hash", "updated_at", "updated_duid", "user_id" FROM "base_sessions";
DROP TABLE "base_sessions";
ALTER TABLE "new_base_sessions" RENAME TO "base_sessions";
CREATE UNIQUE INDEX "base_sessions_token_hash_deleted_at_key" ON "base_sessions"("token_hash", "deleted_at");
CREATE UNIQUE INDEX "base_sessions_key_deleted_at_key" ON "base_sessions"("key", "deleted_at");
CREATE TABLE "new_base_oidc_login_requests" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "request_id" TEXT NOT NULL,
    "issuer" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "nonce" TEXT NOT NULL,
    "code_verifier" TEXT NOT NULL,
    "return_path" TEXT NOT NULL DEFAULT '/',
    "expires_at" BIGINT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "subject" TEXT NOT NULL DEFAULT '',
    "claims" TEXT NOT NULL DEFAULT '{}',
    "credential" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_base_oidc_login_requests" ("claims", "code_verifier", "created_at", "created_duid", "credential", "deleted_at", "expires_at", "id", "issuer", "nonce", "owner_bid", "owner_tid", "owner_uid", "request_id", "return_path", "state", "status", "subject", "updated_at", "updated_duid") SELECT "claims", "code_verifier", "created_at", "created_duid", "credential", "deleted_at", "expires_at", "id", "issuer", "nonce", "owner_bid", "owner_tid", "owner_uid", "request_id", "return_path", "state", "status", "subject", "updated_at", "updated_duid" FROM "base_oidc_login_requests";
DROP TABLE "base_oidc_login_requests";
ALTER TABLE "new_base_oidc_login_requests" RENAME TO "base_oidc_login_requests";
CREATE UNIQUE INDEX "base_oidc_login_requests_request_id_deleted_at_key" ON "base_oidc_login_requests"("request_id", "deleted_at");
CREATE UNIQUE INDEX "base_oidc_login_requests_state_deleted_at_key" ON "base_oidc_login_requests"("state", "deleted_at");
CREATE UNIQUE INDEX "base_oidc_login_requests_key_deleted_at_key" ON "base_oidc_login_requests"("key", "deleted_at");
CREATE TABLE "new_base_oidc_users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "issuer" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "profile" TEXT NOT NULL DEFAULT '{}'
);
INSERT INTO "new_base_oidc_users" ("created_at", "created_duid", "deleted_at", "id", "issuer", "owner_bid", "owner_tid", "owner_uid", "profile", "subject", "updated_at", "updated_duid", "user_id") SELECT "created_at", "created_duid", "deleted_at", "id", "issuer", "owner_bid", "owner_tid", "owner_uid", "profile", "subject", "updated_at", "updated_duid", "user_id" FROM "base_oidc_users";
DROP TABLE "base_oidc_users";
ALTER TABLE "new_base_oidc_users" RENAME TO "base_oidc_users";
CREATE UNIQUE INDEX "base_oidc_users_owner_tid_issuer_subject_deleted_at_key" ON "base_oidc_users"("owner_tid", "issuer", "subject", "deleted_at");
CREATE UNIQUE INDEX "base_oidc_users_key_deleted_at_key" ON "base_oidc_users"("key", "deleted_at");
CREATE TABLE "new_base_oidc_sessions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "issuer" TEXT NOT NULL,
    "sid" TEXT NOT NULL,
    "session_id" BIGINT NOT NULL
);
INSERT INTO "new_base_oidc_sessions" ("created_at", "created_duid", "deleted_at", "id", "issuer", "owner_bid", "owner_tid", "owner_uid", "session_id", "sid", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "id", "issuer", "owner_bid", "owner_tid", "owner_uid", "session_id", "sid", "updated_at", "updated_duid" FROM "base_oidc_sessions";
DROP TABLE "base_oidc_sessions";
ALTER TABLE "new_base_oidc_sessions" RENAME TO "base_oidc_sessions";
CREATE UNIQUE INDEX "base_oidc_sessions_session_id_deleted_at_key" ON "base_oidc_sessions"("session_id", "deleted_at");
CREATE UNIQUE INDEX "base_oidc_sessions_issuer_sid_deleted_at_key" ON "base_oidc_sessions"("issuer", "sid", "deleted_at");
CREATE UNIQUE INDEX "base_oidc_sessions_key_deleted_at_key" ON "base_oidc_sessions"("key", "deleted_at");
CREATE TABLE "new_base_device_users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT
);
INSERT INTO "new_base_device_users" ("created_at", "created_duid", "deleted_at", "device_id", "id", "last_seen_at", "owner_bid", "owner_tid", "owner_uid", "revoked_at", "status", "updated_at", "updated_duid", "user_id") SELECT "created_at", "created_duid", "deleted_at", "device_id", "id", "last_seen_at", "owner_bid", "owner_tid", "owner_uid", "revoked_at", "status", "updated_at", "updated_duid", "user_id" FROM "base_device_users";
DROP TABLE "base_device_users";
ALTER TABLE "new_base_device_users" RENAME TO "base_device_users";
CREATE UNIQUE INDEX "base_device_users_device_id_user_id_deleted_at_key" ON "base_device_users"("device_id", "user_id", "deleted_at");
CREATE UNIQUE INDEX "base_device_users_key_deleted_at_key" ON "base_device_users"("key", "deleted_at");
CREATE TABLE "new_base_device_snapshots" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "fingerprint" TEXT NOT NULL DEFAULT '{}',
    "ip_address" TEXT NOT NULL DEFAULT '',
    "network_info" TEXT NOT NULL DEFAULT '{}',
    "user_agent" TEXT NOT NULL DEFAULT '',
    "platform" TEXT NOT NULL DEFAULT '',
    "screen_width" INTEGER NOT NULL DEFAULT 0,
    "screen_height" INTEGER NOT NULL DEFAULT 0,
    "captured_at" BIGINT NOT NULL
);
INSERT INTO "new_base_device_snapshots" ("captured_at", "created_at", "created_duid", "deleted_at", "device_id", "fingerprint", "id", "ip_address", "network_info", "owner_bid", "owner_tid", "owner_uid", "platform", "screen_height", "screen_width", "updated_at", "updated_duid", "user_agent") SELECT "captured_at", "created_at", "created_duid", "deleted_at", "device_id", "fingerprint", "id", "ip_address", "network_info", "owner_bid", "owner_tid", "owner_uid", "platform", "screen_height", "screen_width", "updated_at", "updated_duid", "user_agent" FROM "base_device_snapshots";
DROP TABLE "base_device_snapshots";
ALTER TABLE "new_base_device_snapshots" RENAME TO "base_device_snapshots";
CREATE UNIQUE INDEX "base_device_snapshots_key_deleted_at_key" ON "base_device_snapshots"("key", "deleted_at");
CREATE TABLE "new_base_approvals" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "operation_id" TEXT NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "scope" TEXT NOT NULL DEFAULT 'admin',
    "request_hostname" TEXT NOT NULL DEFAULT '',
    "request_path" TEXT NOT NULL DEFAULT '',
    "table_name" TEXT NOT NULL,
    "row_id" BIGINT NOT NULL,
    "action" TEXT NOT NULL,
    "changes" TEXT NOT NULL DEFAULT '{}',
    "review_status" TEXT NOT NULL DEFAULT 'none',
    "data_status" TEXT NOT NULL DEFAULT 'applied',
    "reviewed_at" BIGINT,
    "reviewed_duid" BIGINT,
    "review_reason" TEXT NOT NULL DEFAULT '',
    "withdrawn_at" BIGINT,
    "withdrawn_duid" BIGINT,
    "reverted_at" BIGINT,
    "reverted_duid" BIGINT,
    "revert_reason" TEXT NOT NULL DEFAULT '',
    "restored_at" BIGINT,
    "restored_duid" BIGINT,
    "restore_reason" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_base_approvals" ("action", "changes", "created_at", "created_duid", "data_status", "deleted_at", "id", "operation_id", "owner_bid", "owner_tid", "owner_uid", "reason", "request_hostname", "request_path", "restore_reason", "restored_at", "restored_duid", "revert_reason", "reverted_at", "reverted_duid", "review_reason", "review_status", "reviewed_at", "reviewed_duid", "row_id", "scope", "table_name", "updated_at", "updated_duid", "withdrawn_at", "withdrawn_duid") SELECT "action", "changes", "created_at", "created_duid", "data_status", "deleted_at", "id", "operation_id", "owner_bid", "owner_tid", "owner_uid", "reason", "request_hostname", "request_path", "restore_reason", "restored_at", "restored_duid", "revert_reason", "reverted_at", "reverted_duid", "review_reason", "review_status", "reviewed_at", "reviewed_duid", "row_id", "scope", "table_name", "updated_at", "updated_duid", "withdrawn_at", "withdrawn_duid" FROM "base_approvals";
DROP TABLE "base_approvals";
ALTER TABLE "new_base_approvals" RENAME TO "base_approvals";
CREATE INDEX "base_approvals_owner_tid_created_at_idx" ON "base_approvals"("owner_tid", "created_at");
CREATE INDEX "base_approvals_owner_bid_created_at_idx" ON "base_approvals"("owner_bid", "created_at");
CREATE INDEX "base_approvals_owner_uid_created_at_idx" ON "base_approvals"("owner_uid", "created_at");
CREATE INDEX "base_approvals_table_name_row_id_created_at_idx" ON "base_approvals"("table_name", "row_id", "created_at");
CREATE INDEX "base_approvals_operation_id_idx" ON "base_approvals"("operation_id");
CREATE INDEX "base_approvals_review_status_created_at_idx" ON "base_approvals"("review_status", "created_at");
CREATE INDEX "base_approvals_scope_created_at_idx" ON "base_approvals"("scope", "created_at");
CREATE UNIQUE INDEX "base_approvals_key_deleted_at_key" ON "base_approvals"("key", "deleted_at");
CREATE TABLE "new_base_user_credentials" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_id" BIGINT NOT NULL,
    "password" TEXT NOT NULL
);
INSERT INTO "new_base_user_credentials" ("created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "password", "updated_at", "updated_duid", "user_id") SELECT "created_at", "created_duid", "deleted_at", "id", "owner_bid", "owner_tid", "owner_uid", "password", "updated_at", "updated_duid", "user_id" FROM "base_user_credentials";
DROP TABLE "base_user_credentials";
ALTER TABLE "new_base_user_credentials" RENAME TO "base_user_credentials";
CREATE UNIQUE INDEX "base_user_credentials_user_id_deleted_at_key" ON "base_user_credentials"("user_id", "deleted_at");
CREATE UNIQUE INDEX "base_user_credentials_key_deleted_at_key" ON "base_user_credentials"("key", "deleted_at");
CREATE TABLE "new_base_user_profiles" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_id" BIGINT NOT NULL,
    "nickname" TEXT,
    "qq" TEXT NOT NULL DEFAULT '',
    "wechat" TEXT NOT NULL DEFAULT '',
    "email" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_base_user_profiles" ("created_at", "created_duid", "deleted_at", "email", "id", "nickname", "owner_bid", "owner_tid", "owner_uid", "qq", "updated_at", "updated_duid", "user_id", "wechat") SELECT "created_at", "created_duid", "deleted_at", "email", "id", "nickname", "owner_bid", "owner_tid", "owner_uid", "qq", "updated_at", "updated_duid", "user_id", "wechat" FROM "base_user_profiles";
DROP TABLE "base_user_profiles";
ALTER TABLE "new_base_user_profiles" RENAME TO "base_user_profiles";
CREATE UNIQUE INDEX "base_user_profiles_user_id_deleted_at_key" ON "base_user_profiles"("user_id", "deleted_at");
CREATE UNIQUE INDEX "base_user_profiles_owner_tid_nickname_deleted_at_key" ON "base_user_profiles"("owner_tid", "nickname", "deleted_at");
CREATE UNIQUE INDEX "base_user_profiles_key_deleted_at_key" ON "base_user_profiles"("key", "deleted_at");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
