-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_sms_phones" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "integration_client_id" BIGINT NOT NULL DEFAULT 0,
    "client_ref" TEXT NOT NULL DEFAULT '',
    "number" TEXT NOT NULL,
    "title" TEXT NOT NULL DEFAULT '',
    "filename" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "bound_at" BIGINT NOT NULL DEFAULT 0,
    "revoked_at" BIGINT,
    "last_check_at" BIGINT
);
INSERT INTO "new_sms_phones" ("bound_at", "client_ref", "created_at", "created_duid", "deleted_at", "id", "integration_client_id", "key", "last_check_at", "number", "owner_bid", "owner_tid", "owner_uid", "queued_at", "revoked_at", "status", "title", "updated_at", "updated_duid") SELECT "bound_at", "client_ref", "created_at", "created_duid", "deleted_at", "id", "integration_client_id", "key", "last_check_at", "number", "owner_bid", "owner_tid", "owner_uid", "queued_at", "revoked_at", "status", "title", "updated_at", "updated_duid" FROM "sms_phones";
DROP TABLE "sms_phones";
ALTER TABLE "new_sms_phones" RENAME TO "sms_phones";
CREATE INDEX "sms_phones_integration_client_id_idx" ON "sms_phones"("integration_client_id");
CREATE UNIQUE INDEX "sms_phones_key_key" ON "sms_phones"("key");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
