-- Generated by Prisma migrate diff. Source: prisma/loki.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE "loki_sources" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "push_user" TEXT NOT NULL,
    "push_secret_hash" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "last_seen_at" BIGINT NOT NULL DEFAULT 0
);

-- CreateIndex
CREATE UNIQUE INDEX "loki_sources_key_key" ON "loki_sources"("key");

-- CreateIndex
CREATE UNIQUE INDEX "loki_sources_owner_tid_host_deleted_at_key" ON "loki_sources"("owner_tid", "host", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "loki_sources_push_user_key" ON "loki_sources"("push_user");
