-- Generated by Prisma migrate diff. Source: prisma/loki.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE "loki_enroll_tokens" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "expires_at" BIGINT NOT NULL DEFAULT 0,
    "max_uses" INTEGER NOT NULL DEFAULT 0,
    "used_count" INTEGER NOT NULL DEFAULT 0,
    "last_used_at" BIGINT NOT NULL DEFAULT 0
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_loki_sources" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "push_user" TEXT NOT NULL,
    "push_secret_hash" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'enabled',
    "last_seen_at" BIGINT NOT NULL DEFAULT 0,
    "agent_token_hash" TEXT NOT NULL DEFAULT '',
    "previous_token_hash" TEXT NOT NULL DEFAULT '',
    "previous_retry_used" BOOLEAN NOT NULL DEFAULT false,
    "token_rotated_at" BIGINT NOT NULL DEFAULT 0,
    "cloned_from_id" BIGINT,
    "fingerprint" TEXT NOT NULL DEFAULT '',
    "clone_pending" BOOLEAN NOT NULL DEFAULT false
);
INSERT INTO "new_loki_sources" ("created_at", "created_duid", "deleted_at", "host", "id", "key", "last_seen_at", "owner_bid", "owner_tid", "owner_uid", "push_secret_hash", "push_user", "queued_at", "status", "title", "updated_at", "updated_duid") SELECT "created_at", "created_duid", "deleted_at", "host", "id", "key", "last_seen_at", "owner_bid", "owner_tid", "owner_uid", "push_secret_hash", "push_user", "queued_at", "status", "title", "updated_at", "updated_duid" FROM "loki_sources";
DROP TABLE "loki_sources";
ALTER TABLE "new_loki_sources" RENAME TO "loki_sources";
CREATE INDEX "loki_sources_cloned_from_id_idx" ON "loki_sources"("cloned_from_id");
CREATE UNIQUE INDEX "loki_sources_key_key" ON "loki_sources"("key");
CREATE UNIQUE INDEX "loki_sources_owner_tid_host_deleted_at_key" ON "loki_sources"("owner_tid", "host", "deleted_at");
CREATE UNIQUE INDEX "loki_sources_push_user_key" ON "loki_sources"("push_user");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE UNIQUE INDEX "loki_enroll_tokens_key_key" ON "loki_enroll_tokens"("key");

-- CreateIndex
CREATE UNIQUE INDEX "loki_enroll_tokens_token_hash_key" ON "loki_enroll_tokens"("token_hash");
