-- Generated by Prisma migrate diff. Source: prisma/global.prisma (d1).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE "global_snowflake_state" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "worker_id" INTEGER NOT NULL,
    "last_timestamp" BIGINT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "global_snowflake_state_worker_id_deleted_at_key" ON "global_snowflake_state"("worker_id", "deleted_at");
