-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (sqlite).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE "sms_phones" ADD COLUMN "last_check_at" BIGINT;
