-- Generated by Prisma migrate diff. Source: prisma/loki.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE `loki_sources` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `title` VARCHAR(191) NOT NULL,
    `host` VARCHAR(191) NOT NULL,
    `push_user` VARCHAR(191) NOT NULL,
    `push_secret_hash` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `last_seen_at` BIGINT NOT NULL DEFAULT 0,

    UNIQUE INDEX `loki_sources_key_key`(`key`),
    UNIQUE INDEX `loki_sources_owner_tid_host_deleted_at_key`(`owner_tid`, `host`, `deleted_at`),
    UNIQUE INDEX `loki_sources_push_user_key`(`push_user`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
