-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (sqlite).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "pve_regions_key_deleted_at_key";

-- DropIndex
DROP INDEX "pve_nodes_key_deleted_at_key";

-- DropIndex
DROP INDEX "pve_instance_flavors_key_deleted_at_key";

-- DropIndex
DROP INDEX "pve_vms_key_deleted_at_key";

-- DropIndex
DROP INDEX "pve_vm_tasks_key_deleted_at_key";

-- CreateIndex
CREATE UNIQUE INDEX "pve_regions_key_key" ON "pve_regions"("key");

-- CreateIndex
CREATE UNIQUE INDEX "pve_nodes_key_key" ON "pve_nodes"("key");

-- CreateIndex
CREATE UNIQUE INDEX "pve_instance_flavors_key_key" ON "pve_instance_flavors"("key");

-- CreateIndex
CREATE UNIQUE INDEX "pve_vms_key_key" ON "pve_vms"("key");

-- CreateIndex
CREATE UNIQUE INDEX "pve_vm_tasks_key_key" ON "pve_vm_tasks"("key");
