-- Generated by Prisma migrate diff. Source: prisma/base.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE `base_tenants` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `key` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `base_tenants_key_deleted_at_key`(`key`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_branches` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `key` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `base_branches_key_owner_tid_deleted_at_key`(`key`, `owner_tid`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_hosts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `hostname` VARCHAR(191) NOT NULL,
    `tenant_id` BIGINT NOT NULL,
    `branch_id` BIGINT NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `base_hosts_hostname_deleted_at_key`(`hostname`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `name` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `roles` VARCHAR(191) NOT NULL DEFAULT '[]',
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `base_users_name_owner_tid_deleted_at_key`(`name`, `owner_tid`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_sessions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `token_hash` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `expires_at` BIGINT NOT NULL,
    `device_id` BIGINT NOT NULL,

    UNIQUE INDEX `base_sessions_token_hash_deleted_at_key`(`token_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_configs` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `key` VARCHAR(191) NOT NULL,
    `value` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `base_configs_key_owner_tid_deleted_at_key`(`key`, `owner_tid`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_bootstrap` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `key` VARCHAR(191) NOT NULL,
    `value` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `base_bootstrap_key_owner_tid_deleted_at_key`(`key`, `owner_tid`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_oidc_login_requests` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `request_id` VARCHAR(191) NOT NULL,
    `issuer` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `nonce` VARCHAR(191) NOT NULL,
    `code_verifier` VARCHAR(191) NOT NULL,
    `return_path` VARCHAR(191) NOT NULL DEFAULT '/',
    `expires_at` BIGINT NOT NULL,

    UNIQUE INDEX `base_oidc_login_requests_request_id_deleted_at_key`(`request_id`, `deleted_at`),
    UNIQUE INDEX `base_oidc_login_requests_state_deleted_at_key`(`state`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_oidc_users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `issuer` VARCHAR(191) NOT NULL,
    `subject` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `profile` VARCHAR(191) NOT NULL DEFAULT '{}',

    UNIQUE INDEX `base_oidc_users_issuer_subject_owner_tid_deleted_at_key`(`issuer`, `subject`, `owner_tid`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_oidc_sessions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `issuer` VARCHAR(191) NOT NULL,
    `sid` VARCHAR(191) NOT NULL,
    `session_id` BIGINT NOT NULL,

    UNIQUE INDEX `base_oidc_sessions_session_id_deleted_at_key`(`session_id`, `deleted_at`),
    UNIQUE INDEX `base_oidc_sessions_issuer_sid_deleted_at_key`(`issuer`, `sid`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_devices` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `fingerprint` JSON NOT NULL,
    `user_agent` VARCHAR(191) NOT NULL DEFAULT '',
    `platform` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_address` VARCHAR(191) NOT NULL DEFAULT '',
    `network_info` JSON NOT NULL,
    `status` ENUM('active', 'revoked') NOT NULL DEFAULT 'active',
    `last_seen_at` BIGINT NOT NULL,
    `revoked_at` BIGINT NULL,

    UNIQUE INDEX `base_devices_key_deleted_at_key`(`key`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_device_users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `device_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `status` ENUM('active', 'revoked') NOT NULL DEFAULT 'active',
    `last_seen_at` BIGINT NOT NULL,
    `revoked_at` BIGINT NULL,

    UNIQUE INDEX `base_device_users_device_id_user_id_deleted_at_key`(`device_id`, `user_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `base_device_snapshots` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `device_id` BIGINT NOT NULL,
    `fingerprint` JSON NOT NULL,
    `ip_address` VARCHAR(191) NOT NULL DEFAULT '',
    `network_info` JSON NOT NULL,
    `user_agent` VARCHAR(191) NOT NULL DEFAULT '',
    `platform` VARCHAR(191) NOT NULL DEFAULT '',
    `screen_width` INTEGER NOT NULL DEFAULT 0,
    `screen_height` INTEGER NOT NULL DEFAULT 0,
    `captured_at` BIGINT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
