-- Generated by Prisma migrate diff. Source: prisma/base.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropTable
DROP TABLE `base_audit_transitions`;

-- CreateTable
CREATE TABLE `base_audit_approvals` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `audit_id` BIGINT NOT NULL,
    `kind` ENUM('approve', 'reject', 'withdraw', 'requeue', 'revert', 'redo') NOT NULL,
    `reason` VARCHAR(191) NOT NULL DEFAULT '',

    INDEX `base_audit_approvals_audit_id_id_idx`(`audit_id`, `id`),
    UNIQUE INDEX `base_audit_approvals_key_key`(`key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
