-- Generated by Prisma migrate diff. Source: prisma/base.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE `base_approvals` ADD COLUMN `row_key` VARCHAR(36) NOT NULL DEFAULT '';
