-- Generated by Prisma migrate diff. Source: prisma/base.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropTable
DROP TABLE `base_audit_entries`;

-- CreateTable
CREATE TABLE `base_approvals` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `operation_id` VARCHAR(191) NOT NULL,
    `reason` VARCHAR(191) NOT NULL DEFAULT '',
    `request_hostname` VARCHAR(191) NOT NULL DEFAULT '',
    `request_path` VARCHAR(191) NOT NULL DEFAULT '',
    `table_name` VARCHAR(191) NOT NULL,
    `row_id` BIGINT NOT NULL,
    `action` ENUM('update', 'soft_delete', 'restore') NOT NULL,
    `changes` JSON NOT NULL,
    `status` ENUM('pending', 'applied', 'rejected', 'withdrawn', 'reverted') NOT NULL DEFAULT 'applied',
    `reviewed_at` BIGINT NULL,
    `reviewed_duid` BIGINT NULL,
    `review_reason` VARCHAR(191) NOT NULL DEFAULT '',
    `withdrawn_at` BIGINT NULL,
    `withdrawn_duid` BIGINT NULL,
    `reverted_at` BIGINT NULL,
    `reverted_duid` BIGINT NULL,
    `revert_reason` VARCHAR(191) NOT NULL DEFAULT '',
    `restored_at` BIGINT NULL,
    `restored_duid` BIGINT NULL,
    `restore_reason` VARCHAR(191) NOT NULL DEFAULT '',

    INDEX `base_approvals_owner_tid_created_at_idx`(`owner_tid`, `created_at`),
    INDEX `base_approvals_owner_bid_created_at_idx`(`owner_bid`, `created_at`),
    INDEX `base_approvals_owner_uid_created_at_idx`(`owner_uid`, `created_at`),
    INDEX `base_approvals_table_name_row_id_created_at_idx`(`table_name`, `row_id`, `created_at`),
    INDEX `base_approvals_operation_id_idx`(`operation_id`),
    INDEX `base_approvals_status_created_at_idx`(`status`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
