-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE `pve_regions` ADD COLUMN `pended_at` BIGINT NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `pve_nodes` ADD COLUMN `pended_at` BIGINT NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `pve_instance_flavors` ADD COLUMN `pended_at` BIGINT NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `pve_vms` ADD COLUMN `pended_at` BIGINT NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `pve_vm_tasks` ADD COLUMN `pended_at` BIGINT NOT NULL DEFAULT 0;
