-- Generated by Prisma migrate diff. Source: prisma/pve.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateIndex
CREATE UNIQUE INDEX `pve_nodes_owner_tid_name_deleted_at_key` ON `pve_nodes`(`owner_tid`, `name`, `deleted_at`);

-- CreateIndex
CREATE UNIQUE INDEX `pve_vms_owner_tid_name_deleted_at_key` ON `pve_vms`(`owner_tid`, `name`, `deleted_at`);
