-- Generated by Prisma migrate diff. Source: prisma/global.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "GlobalEnabledStatus" AS ENUM ('enabled', 'disabled');

-- CreateEnum
CREATE TYPE "GlobalMigrationStatus" AS ENUM ('creating', 'migrating', 'ready', 'failed');

-- CreateEnum
CREATE TYPE "GlobalPublicationStatus" AS ENUM ('reviewing', 'ready', 'rejected', 'failed');

-- CreateTable
CREATE TABLE "global_sites" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "base_site_key" TEXT,
    "dsn" TEXT NOT NULL DEFAULT '',
    "dsn_password" TEXT,
    "database_binding" TEXT NOT NULL DEFAULT '',
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',
    "migration_status" "GlobalMigrationStatus" NOT NULL DEFAULT 'ready',
    "is_default" INTEGER NOT NULL DEFAULT 0,
    "is_system" INTEGER NOT NULL DEFAULT 0,
    "passport_sso_enabled" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "global_sites_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_site_hosts" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "hostname" TEXT NOT NULL,
    "site_key" TEXT NOT NULL,
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_site_hosts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_credentials" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "account_id" TEXT NOT NULL DEFAULT '',
    "access_key_id" TEXT NOT NULL DEFAULT '',
    "access_key_secret" TEXT NOT NULL DEFAULT '',
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_cloud_credentials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_object_storage_buckets" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "cloud_credential_id" BIGINT NOT NULL,
    "endpoint" TEXT NOT NULL,
    "region" TEXT NOT NULL DEFAULT '',
    "bucket" TEXT NOT NULL,
    "path_style" INTEGER NOT NULL DEFAULT 0,
    "public_base_url" TEXT NOT NULL DEFAULT '',
    "extra_config" TEXT NOT NULL DEFAULT '{}',
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_cloud_object_storage_buckets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_object_storage_bindings" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "site_key" TEXT NOT NULL,
    "bucket_id" BIGINT NOT NULL,
    "key_prefix" TEXT NOT NULL DEFAULT '',
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_cloud_object_storage_bindings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_object_storage_binding_purposes" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "binding_id" BIGINT NOT NULL,
    "site_key" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "is_default" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "global_cloud_object_storage_binding_purposes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_telegram_bots" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "secret_token" TEXT NOT NULL,
    "webhook_hostname" TEXT NOT NULL,
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_telegram_bots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_email_channels" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "cloud_credential_id" BIGINT NOT NULL,
    "region" TEXT NOT NULL,
    "account_name" TEXT NOT NULL,
    "from_alias" TEXT NOT NULL,
    "reply_to_address" INTEGER NOT NULL DEFAULT 0,
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_cloud_email_channels_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_email_templates" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "type" TEXT NOT NULL DEFAULT 'email_verification',
    "title" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "body_html" TEXT NOT NULL,
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_cloud_email_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_email_bindings" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "site_key" TEXT NOT NULL,
    "channel_id" BIGINT NOT NULL,
    "template_id" BIGINT NOT NULL,
    "purpose" TEXT NOT NULL,
    "is_default" INTEGER NOT NULL DEFAULT 0,
    "status" "GlobalEnabledStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "global_cloud_email_bindings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_cloud_email_template_publications" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "template_id" BIGINT NOT NULL,
    "cloud_credential_id" BIGINT NOT NULL,
    "region" TEXT NOT NULL,
    "provider_template_id" TEXT NOT NULL,
    "content_hash" TEXT NOT NULL DEFAULT '',
    "status" "GlobalPublicationStatus" NOT NULL,

    CONSTRAINT "global_cloud_email_template_publications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_snowflake_state" (
    "id" BIGSERIAL NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "worker_id" INTEGER NOT NULL,
    "last_timestamp" BIGINT NOT NULL,

    CONSTRAINT "global_snowflake_state_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "global_sites_key_key" ON "global_sites"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_site_hosts_hostname_key" ON "global_site_hosts"("hostname");

-- CreateIndex
CREATE UNIQUE INDEX "global_site_hosts_key_key" ON "global_site_hosts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_credentials_title_key" ON "global_cloud_credentials"("title");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_credentials_key_key" ON "global_cloud_credentials"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_buckets_cloud_credential_id_end_key" ON "global_cloud_object_storage_buckets"("cloud_credential_id", "endpoint", "bucket");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_buckets_key_key" ON "global_cloud_object_storage_buckets"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_id_site_key_key" ON "global_cloud_object_storage_bindings"("id", "site_key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_site_key_bucket_id_key_key" ON "global_cloud_object_storage_bindings"("site_key", "bucket_id", "key_prefix");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_key_key" ON "global_cloud_object_storage_bindings"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_binding_purposes_binding_id_pur_key" ON "global_cloud_object_storage_binding_purposes"("binding_id", "purpose");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_binding_purposes_key_key" ON "global_cloud_object_storage_binding_purposes"("key");

-- CreateIndex
CREATE INDEX "global_telegram_bots_webhook_hostname_idx" ON "global_telegram_bots"("webhook_hostname");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_title_key" ON "global_telegram_bots"("title");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_token_key" ON "global_telegram_bots"("token");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_username_key" ON "global_telegram_bots"("username");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_key_key" ON "global_telegram_bots"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_channels_cloud_credential_id_region_acco_key" ON "global_cloud_email_channels"("cloud_credential_id", "region", "account_name");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_channels_key_key" ON "global_cloud_email_channels"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_templates_key_key" ON "global_cloud_email_templates"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_bindings_site_key_channel_id_template_id_key" ON "global_cloud_email_bindings"("site_key", "channel_id", "template_id", "purpose");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_bindings_key_key" ON "global_cloud_email_bindings"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_template_publications_template_id_cloud__key" ON "global_cloud_email_template_publications"("template_id", "cloud_credential_id", "region");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_template_publications_key_key" ON "global_cloud_email_template_publications"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_snowflake_state_worker_id_key" ON "global_snowflake_state"("worker_id");
