-- Generated by Prisma migrate diff. Source: prisma/global.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "global_sites_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_site_hosts_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_credentials_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_object_storage_buckets_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_object_storage_bindings_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_object_storage_binding_purposes_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_telegram_bots_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_email_channels_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_email_templates_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_email_bindings_key_deleted_at_key";

-- DropIndex
DROP INDEX "global_cloud_email_template_publications_key_deleted_at_key";

-- CreateIndex
CREATE UNIQUE INDEX "global_sites_key_key" ON "global_sites"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_site_hosts_key_key" ON "global_site_hosts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_credentials_key_key" ON "global_cloud_credentials"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_buckets_key_key" ON "global_cloud_object_storage_buckets"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_bindings_key_key" ON "global_cloud_object_storage_bindings"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_object_storage_binding_purposes_key_key" ON "global_cloud_object_storage_binding_purposes"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_telegram_bots_key_key" ON "global_telegram_bots"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_channels_key_key" ON "global_cloud_email_channels"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_templates_key_key" ON "global_cloud_email_templates"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_bindings_key_key" ON "global_cloud_email_bindings"("key");

-- CreateIndex
CREATE UNIQUE INDEX "global_cloud_email_template_publications_key_key" ON "global_cloud_email_template_publications"("key");
