-- Generated by Prisma migrate diff. Source: prisma/global.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE "global_cloud_object_storage_bindings" ADD COLUMN     "purposes" TEXT NOT NULL DEFAULT '[]';

-- DropTable
DROP TABLE "global_cloud_object_storage_binding_purposes";
