-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE `sms_integration_clients` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `name` VARCHAR(64) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `binding_scope` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `last_used_at` BIGINT NULL,

    UNIQUE INDEX `sms_integration_clients_key_key`(`key`),
    UNIQUE INDEX `sms_integration_clients_owner_tid_name_deleted_at_key`(`owner_tid`, `name`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_integration_client_keys` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `integration_client_id` BIGINT NOT NULL,
    `kid` VARCHAR(64) NOT NULL,
    `public_key` VARCHAR(191) NOT NULL,
    `status` ENUM('active', 'retired') NOT NULL DEFAULT 'active',
    `retired_at` BIGINT NULL,

    INDEX `sms_integration_client_keys_integration_client_id_idx`(`integration_client_id`),
    UNIQUE INDEX `sms_integration_client_keys_key_key`(`key`),
    UNIQUE INDEX `sms_integration_client_keys_integration_client_id_kid_key`(`integration_client_id`, `kid`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_phones` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `number` VARCHAR(32) NOT NULL,
    `title` VARCHAR(191) NOT NULL DEFAULT '',
    `status` ENUM('enabled', 'disabled', 'revoked') NOT NULL DEFAULT 'enabled',
    `bound_at` BIGINT NOT NULL DEFAULT 0,
    `revoked_at` BIGINT NULL,

    UNIQUE INDEX `sms_phones_key_key`(`key`),
    UNIQUE INDEX `sms_phones_owner_tid_number_deleted_at_key`(`owner_tid`, `number`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_shortcut_tokens` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `token_sha256` VARCHAR(64) NOT NULL,
    `phone_id` BIGINT NULL,
    `status` ENUM('pending', 'available', 'bound', 'revoked') NOT NULL DEFAULT 'pending',
    `idempotency_token` VARCHAR(64) NOT NULL,
    `last_used_at` BIGINT NULL,

    INDEX `sms_shortcut_tokens_phone_id_idx`(`phone_id`),
    UNIQUE INDEX `sms_shortcut_tokens_key_key`(`key`),
    UNIQUE INDEX `sms_shortcut_tokens_token_sha256_key`(`token_sha256`),
    UNIQUE INDEX `sms_shortcut_tokens_idempotency_token_key`(`idempotency_token`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_shortcut_artifacts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `token_id` BIGINT NOT NULL,
    `object_key` VARCHAR(191) NOT NULL,
    `file_sha256` VARCHAR(64) NOT NULL,
    `size_bytes` BIGINT NOT NULL DEFAULT 0,
    `content_type` VARCHAR(191) NOT NULL,
    `version` INTEGER NOT NULL DEFAULT 1,
    `generator_machine_id` BIGINT NOT NULL,
    `status` ENUM('ready', 'revoked') NOT NULL DEFAULT 'ready',

    INDEX `sms_shortcut_artifacts_token_id_idx`(`token_id`),
    INDEX `sms_shortcut_artifacts_generator_machine_id_idx`(`generator_machine_id`),
    UNIQUE INDEX `sms_shortcut_artifacts_key_key`(`key`),
    UNIQUE INDEX `sms_shortcut_artifacts_object_key_key`(`object_key`),
    UNIQUE INDEX `sms_shortcut_artifacts_token_id_version_key`(`token_id`, `version`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_messages` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `phone_id` BIGINT NOT NULL,
    `content` VARCHAR(191) NOT NULL,
    `recipients` VARCHAR(191) NOT NULL DEFAULT '',
    `sender` VARCHAR(191) NOT NULL DEFAULT '',
    `received_at` BIGINT NOT NULL DEFAULT 0,
    `payload_hash` VARCHAR(64) NOT NULL,

    INDEX `sms_messages_phone_id_idx`(`phone_id`),
    INDEX `sms_messages_received_at_idx`(`received_at`),
    UNIQUE INDEX `sms_messages_key_key`(`key`),
    UNIQUE INDEX `sms_messages_phone_id_payload_hash_key`(`phone_id`, `payload_hash`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_ticket_nonces` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `integration_client_id` BIGINT NOT NULL,
    `nonce` VARCHAR(64) NOT NULL,
    `expires_at` BIGINT NOT NULL DEFAULT 0,

    INDEX `sms_ticket_nonces_integration_client_id_idx`(`integration_client_id`),
    INDEX `sms_ticket_nonces_expires_at_idx`(`expires_at`),
    UNIQUE INDEX `sms_ticket_nonces_key_key`(`key`),
    UNIQUE INDEX `sms_ticket_nonces_integration_client_id_nonce_key`(`integration_client_id`, `nonce`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_access_keys` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `secret_hash` VARCHAR(191) NOT NULL,
    `secret_prefix` VARCHAR(16) NOT NULL,
    `scope` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `expires_at` BIGINT NULL,
    `revoked_at` BIGINT NULL,

    UNIQUE INDEX `sms_access_keys_key_key`(`key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_push_endpoints` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `url` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `phone_id` BIGINT NULL,
    `last_success_at` BIGINT NULL,
    `last_error` VARCHAR(191) NOT NULL DEFAULT '',

    INDEX `sms_push_endpoints_phone_id_idx`(`phone_id`),
    UNIQUE INDEX `sms_push_endpoints_key_key`(`key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_push_deliveries` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `message_id` BIGINT NOT NULL,
    `push_endpoint_id` BIGINT NOT NULL,
    `delivery_id` VARCHAR(64) NOT NULL,
    `status` ENUM('pending', 'sending', 'succeeded', 'failed') NOT NULL DEFAULT 'pending',
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `next_attempt_at` BIGINT NOT NULL DEFAULT 0,
    `last_error` VARCHAR(191) NOT NULL DEFAULT '',

    INDEX `sms_push_deliveries_message_id_idx`(`message_id`),
    INDEX `sms_push_deliveries_push_endpoint_id_idx`(`push_endpoint_id`),
    INDEX `sms_push_deliveries_next_attempt_at_idx`(`next_attempt_at`),
    UNIQUE INDEX `sms_push_deliveries_key_key`(`key`),
    UNIQUE INDEX `sms_push_deliveries_delivery_id_key`(`delivery_id`),
    UNIQUE INDEX `sms_push_deliveries_message_id_push_endpoint_id_key`(`message_id`, `push_endpoint_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sms_generator_machines` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(36) NOT NULL,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `queued_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `name` VARCHAR(64) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `secret_hash` VARCHAR(191) NOT NULL,
    `secret_prefix` VARCHAR(16) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `last_used_at` BIGINT NULL,

    UNIQUE INDEX `sms_generator_machines_key_key`(`key`),
    UNIQUE INDEX `sms_generator_machines_owner_tid_name_deleted_at_key`(`owner_tid`, `name`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
