-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX `sms_phones_owner_tid_owner_uid_integration_client_id_client__key` ON `sms_phones`;
