-- Generated by Prisma migrate diff. Source: prisma/loki.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE "loki_sources" ADD COLUMN     "agent_token_hash" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "clone_pending" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "cloned_from_id" BIGINT,
ADD COLUMN     "fingerprint" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "previous_retry_used" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "previous_token_hash" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "token_rotated_at" BIGINT NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "loki_enroll_tokens" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "title" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "status" "LokiEnabledStatus" NOT NULL DEFAULT 'enabled',
    "expires_at" BIGINT NOT NULL DEFAULT 0,
    "max_uses" INTEGER NOT NULL DEFAULT 0,
    "used_count" INTEGER NOT NULL DEFAULT 0,
    "last_used_at" BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT "loki_enroll_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "loki_enroll_tokens_key_key" ON "loki_enroll_tokens"("key");

-- CreateIndex
CREATE UNIQUE INDEX "loki_enroll_tokens_token_hash_key" ON "loki_enroll_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "loki_sources_cloned_from_id_idx" ON "loki_sources"("cloned_from_id");
