-- Generated by Prisma migrate diff. Source: prisma/global.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE `global_sites` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `site_key` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `base_site_key` VARCHAR(191) NULL,
    `dsn` VARCHAR(191) NOT NULL DEFAULT '',
    `dsn_password` VARCHAR(191) NULL,
    `database_binding` VARCHAR(191) NOT NULL DEFAULT '',
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `migration_status` ENUM('creating', 'migrating', 'ready', 'failed') NOT NULL DEFAULT 'ready',
    `is_default` INTEGER NOT NULL DEFAULT 0,
    `is_system` INTEGER NOT NULL DEFAULT 0,
    `passport_sso_enabled` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `global_sites_site_key_key`(`site_key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_site_hosts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `hostname` VARCHAR(191) NOT NULL,
    `site_key` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_site_hosts_hostname_key`(`hostname`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_credentials` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `name` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `account_id` VARCHAR(191) NOT NULL DEFAULT '',
    `access_key_id` VARCHAR(191) NOT NULL DEFAULT '',
    `access_key_secret` VARCHAR(191) NOT NULL DEFAULT '',
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_cloud_credentials_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_object_storage_buckets` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `cloud_credential_id` BIGINT NOT NULL,
    `endpoint` VARCHAR(191) NOT NULL,
    `region` VARCHAR(191) NOT NULL DEFAULT '',
    `bucket` VARCHAR(191) NOT NULL,
    `path_style` INTEGER NOT NULL DEFAULT 0,
    `public_base_url` VARCHAR(191) NOT NULL DEFAULT '',
    `extra_config` VARCHAR(191) NOT NULL DEFAULT '{}',
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_cloud_object_storage_buckets_cloud_credential_id_endp_key`(`cloud_credential_id`, `endpoint`, `bucket`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_object_storage_bindings` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `site_key` VARCHAR(191) NOT NULL,
    `bucket_id` BIGINT NOT NULL,
    `key_prefix` VARCHAR(191) NOT NULL DEFAULT '',
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_cloud_object_storage_bindings_id_site_key_key`(`id`, `site_key`),
    UNIQUE INDEX `global_cloud_object_storage_bindings_site_key_bucket_id_key__key`(`site_key`, `bucket_id`, `key_prefix`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_object_storage_binding_purposes` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL DEFAULT 0,
    `updated_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `binding_id` BIGINT NOT NULL,
    `site_key` VARCHAR(191) NOT NULL,
    `purpose` VARCHAR(191) NOT NULL,
    `is_default` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `global_cloud_object_storage_binding_purposes_binding_id_purp_key`(`binding_id`, `purpose`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_telegram_bots` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `name` VARCHAR(191) NOT NULL,
    `bot_token` VARCHAR(191) NOT NULL,
    `bot_username` VARCHAR(191) NOT NULL,
    `secret_token` VARCHAR(191) NOT NULL,
    `webhook_hostname` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_telegram_bots_name_key`(`name`),
    UNIQUE INDEX `global_telegram_bots_bot_token_key`(`bot_token`),
    UNIQUE INDEX `global_telegram_bots_bot_username_key`(`bot_username`),
    INDEX `global_telegram_bots_webhook_hostname_idx`(`webhook_hostname`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_email_channels` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `cloud_credential_id` BIGINT NOT NULL,
    `region` VARCHAR(191) NOT NULL,
    `account_name` VARCHAR(191) NOT NULL,
    `from_alias` VARCHAR(191) NOT NULL,
    `reply_to_address` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_cloud_email_channels_cloud_credential_id_region_accou_key`(`cloud_credential_id`, `region`, `account_name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_email_templates` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `template_key` VARCHAR(191) NOT NULL,
    `template_type` VARCHAR(191) NOT NULL DEFAULT 'email_verification',
    `name` VARCHAR(191) NOT NULL,
    `subject` VARCHAR(191) NOT NULL,
    `body_text` VARCHAR(191) NOT NULL,
    `body_html` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_cloud_email_templates_template_key_key`(`template_key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_email_bindings` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `site_key` VARCHAR(191) NOT NULL,
    `channel_id` BIGINT NOT NULL,
    `template_id` BIGINT NOT NULL,
    `purpose` VARCHAR(191) NOT NULL,
    `is_default` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `global_cloud_email_bindings_site_key_channel_id_template_id__key`(`site_key`, `channel_id`, `template_id`, `purpose`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `global_cloud_email_template_publications` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `template_id` BIGINT NOT NULL,
    `cloud_credential_id` BIGINT NOT NULL,
    `region` VARCHAR(191) NOT NULL,
    `provider_template_id` VARCHAR(191) NOT NULL,
    `content_hash` VARCHAR(191) NOT NULL DEFAULT '',
    `status` ENUM('reviewing', 'ready', 'rejected', 'failed') NOT NULL,

    UNIQUE INDEX `global_cloud_email_template_publications_template_id_cloud_c_key`(`template_id`, `cloud_credential_id`, `region`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
