-- Generated by Prisma migrate diff. Source: prisma/global.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX `global_cloud_credentials_name_deleted_at_key` ON `global_cloud_credentials`;

-- DropIndex
DROP INDEX `global_telegram_bots_name_deleted_at_key` ON `global_telegram_bots`;

-- AlterTable
ALTER TABLE `global_sites` DROP COLUMN `name`,
    ADD COLUMN `title` VARCHAR(191) NOT NULL;

-- AlterTable
ALTER TABLE `global_cloud_credentials` DROP COLUMN `name`,
    ADD COLUMN `title` VARCHAR(191) NOT NULL;

-- AlterTable
ALTER TABLE `global_telegram_bots` DROP COLUMN `name`,
    ADD COLUMN `title` VARCHAR(191) NOT NULL;

-- AlterTable
ALTER TABLE `global_cloud_email_templates` DROP COLUMN `name`,
    ADD COLUMN `title` VARCHAR(191) NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_credentials_title_deleted_at_key` ON `global_cloud_credentials`(`title`, `deleted_at`);

-- CreateIndex
CREATE UNIQUE INDEX `global_telegram_bots_title_deleted_at_key` ON `global_telegram_bots`(`title`, `deleted_at`);
