-- Generated by Prisma migrate diff. Source: prisma/global.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX `global_site_hosts_hostname_deleted_at_key` ON `global_site_hosts`;

-- DropIndex
DROP INDEX `global_cloud_credentials_title_deleted_at_key` ON `global_cloud_credentials`;

-- DropIndex
DROP INDEX `global_cloud_object_storage_buckets_cloud_credential_id_endp_key` ON `global_cloud_object_storage_buckets`;

-- DropIndex
DROP INDEX `global_cloud_object_storage_bindings_id_site_key_deleted_at_key` ON `global_cloud_object_storage_bindings`;

-- DropIndex
DROP INDEX `global_cloud_object_storage_bindings_site_key_bucket_id_key__key` ON `global_cloud_object_storage_bindings`;

-- DropIndex
DROP INDEX `global_cloud_object_storage_binding_purposes_binding_id_purp_key` ON `global_cloud_object_storage_binding_purposes`;

-- DropIndex
DROP INDEX `global_telegram_bots_title_deleted_at_key` ON `global_telegram_bots`;

-- DropIndex
DROP INDEX `global_telegram_bots_token_deleted_at_key` ON `global_telegram_bots`;

-- DropIndex
DROP INDEX `global_telegram_bots_username_deleted_at_key` ON `global_telegram_bots`;

-- DropIndex
DROP INDEX `global_cloud_email_channels_cloud_credential_id_region_accou_key` ON `global_cloud_email_channels`;

-- DropIndex
DROP INDEX `global_cloud_email_bindings_site_key_channel_id_template_id__key` ON `global_cloud_email_bindings`;

-- DropIndex
DROP INDEX `global_cloud_email_template_publications_template_id_cloud_c_key` ON `global_cloud_email_template_publications`;

-- DropIndex
DROP INDEX `global_snowflake_state_worker_id_deleted_at_key` ON `global_snowflake_state`;

-- CreateIndex
CREATE UNIQUE INDEX `global_site_hosts_hostname_key` ON `global_site_hosts`(`hostname`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_credentials_title_key` ON `global_cloud_credentials`(`title`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_object_storage_buckets_cloud_credential_id_endp_key` ON `global_cloud_object_storage_buckets`(`cloud_credential_id`, `endpoint`, `bucket`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_object_storage_bindings_id_site_key_key` ON `global_cloud_object_storage_bindings`(`id`, `site_key`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_object_storage_bindings_site_key_bucket_id_key__key` ON `global_cloud_object_storage_bindings`(`site_key`, `bucket_id`, `key_prefix`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_object_storage_binding_purposes_binding_id_purp_key` ON `global_cloud_object_storage_binding_purposes`(`binding_id`, `purpose`);

-- CreateIndex
CREATE UNIQUE INDEX `global_telegram_bots_title_key` ON `global_telegram_bots`(`title`);

-- CreateIndex
CREATE UNIQUE INDEX `global_telegram_bots_token_key` ON `global_telegram_bots`(`token`);

-- CreateIndex
CREATE UNIQUE INDEX `global_telegram_bots_username_key` ON `global_telegram_bots`(`username`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_email_channels_cloud_credential_id_region_accou_key` ON `global_cloud_email_channels`(`cloud_credential_id`, `region`, `account_name`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_email_bindings_site_key_channel_id_template_id__key` ON `global_cloud_email_bindings`(`site_key`, `channel_id`, `template_id`, `purpose`);

-- CreateIndex
CREATE UNIQUE INDEX `global_cloud_email_template_publications_template_id_cloud_c_key` ON `global_cloud_email_template_publications`(`template_id`, `cloud_credential_id`, `region`);

-- CreateIndex
CREATE UNIQUE INDEX `global_snowflake_state_worker_id_key` ON `global_snowflake_state`(`worker_id`);
