-- Generated by Prisma migrate diff. Source: prisma/global.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE `global_site_hosts` ADD COLUMN `client_key` VARCHAR(191) NOT NULL DEFAULT '';
