-- Generated by Prisma migrate diff. Source: prisma/passport.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "PassportAccountStatus" AS ENUM ('enabled', 'disabled');

-- CreateEnum
CREATE TYPE "PassportOtpStatus" AS ENUM ('pending', 'expired', 'used');

-- CreateEnum
CREATE TYPE "PassportTelegramUpdateStatus" AS ENUM ('processing', 'completed', 'failed');

-- CreateEnum
CREATE TYPE "PassportTelegramChoiceStatus" AS ENUM ('pending', 'confirmed', 'cancelled', 'expired');

-- CreateEnum
CREATE TYPE "PassportLoginChallengeStatus" AS ENUM ('pending', 'approved', 'denied', 'consumed', 'expired');

-- CreateEnum
CREATE TYPE "PassportSsoStatus" AS ENUM ('pending', 'consumed', 'expired');

-- CreateEnum
CREATE TYPE "PassportExternalPendingStatus" AS ENUM ('pending', 'expired', 'completed');

-- CreateEnum
CREATE TYPE "PassportQrStatus" AS ENUM ('pending', 'authorized', 'consumed');

-- CreateEnum
CREATE TYPE "PassportSigningKeyStatus" AS ENUM ('active', 'retired');

-- CreateEnum
CREATE TYPE "PassportDeviceStatus" AS ENUM ('active', 'revoked');

-- CreateTable
CREATE TABLE "passport_users" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "name" TEXT NOT NULL,
    "status" "PassportAccountStatus" NOT NULL DEFAULT 'enabled',

    CONSTRAINT "passport_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_user_email_otps" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "otp_id" TEXT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "email" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "status" "PassportOtpStatus" NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_user_email_otps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_user_credentials" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" VARCHAR(36) NOT NULL,
    "password" JSONB NOT NULL,

    CONSTRAINT "passport_user_credentials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_sessions" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "device_id" BIGINT NOT NULL,

    CONSTRAINT "passport_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_devices" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "fingerprint" JSONB NOT NULL DEFAULT '{}',
    "user_agent" TEXT NOT NULL DEFAULT '',
    "platform" TEXT NOT NULL DEFAULT '',
    "ip_address" TEXT NOT NULL DEFAULT '',
    "network_info" JSONB NOT NULL DEFAULT '{}',
    "status" "PassportDeviceStatus" NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,

    CONSTRAINT "passport_devices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_device_users" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "device_id" BIGINT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "status" "PassportDeviceStatus" NOT NULL DEFAULT 'active',
    "last_seen_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,

    CONSTRAINT "passport_device_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_telegram_accounts" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" VARCHAR(36) NOT NULL,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "nickname" TEXT NOT NULL,

    CONSTRAINT "passport_telegram_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_oauth_accounts" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" VARCHAR(36) NOT NULL,
    "provider" TEXT NOT NULL,
    "provider_user_id" TEXT NOT NULL,

    CONSTRAINT "passport_oauth_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_emails" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "email" TEXT NOT NULL,
    "verified" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "passport_emails_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_user_emails" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" VARCHAR(36) NOT NULL,
    "email_id" BIGINT NOT NULL,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "passport_user_emails_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_telegram_email_otps" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "email" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "status" "PassportOtpStatus" NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_telegram_email_otps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_telegram_menus" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "message_id" BIGINT NOT NULL,
    "mode" TEXT NOT NULL,

    CONSTRAINT "passport_telegram_menus_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_telegram_updates" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "update_id" BIGINT NOT NULL,
    "status" "PassportTelegramUpdateStatus" NOT NULL,

    CONSTRAINT "passport_telegram_updates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_telegram_identity_choices" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "target_user_key" VARCHAR(36) NOT NULL,
    "email" TEXT NOT NULL,
    "status" "PassportTelegramChoiceStatus" NOT NULL,
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_telegram_identity_choices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_login_challenges" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "challenge_id" TEXT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "expected_number" INTEGER NOT NULL,
    "status" "PassportLoginChallengeStatus" NOT NULL,
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_login_challenges_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_sso_requests" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "request_id" TEXT NOT NULL,
    "target_site_key" TEXT NOT NULL,
    "target_hostname" TEXT NOT NULL,
    "status" "PassportSsoStatus" NOT NULL,
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_sso_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_login_tickets" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "target_site_key" TEXT NOT NULL,
    "target_hostname" TEXT NOT NULL,
    "status" "PassportSsoStatus" NOT NULL,
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_login_tickets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_site_sessions" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "session_id" TEXT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "site_key" TEXT NOT NULL,
    "hostname" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_site_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_group_prompts" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "chat_id" BIGINT NOT NULL,
    "actor_id" BIGINT NOT NULL,
    "state_json" TEXT NOT NULL DEFAULT '{}',
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_group_prompts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_external_email_otps" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "otp_id" TEXT NOT NULL,
    "pending_identity_hash" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "status" "PassportOtpStatus" NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_external_email_otps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_external_identities" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" VARCHAR(36) NOT NULL,
    "provider" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "profile" TEXT NOT NULL DEFAULT '{}',

    CONSTRAINT "passport_external_identities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_external_login_states" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "id_hash" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "code_verifier" TEXT NOT NULL,
    "nonce" TEXT NOT NULL,
    "redirect_uri" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "consumed_at" BIGINT,
    "qr_status" "PassportQrStatus" NOT NULL DEFAULT 'pending',
    "qr_user_key" VARCHAR(36),
    "oidc_request_id" TEXT,

    CONSTRAINT "passport_external_login_states_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_external_pending_identities" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "id_hash" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "nickname" TEXT NOT NULL,
    "profile" TEXT NOT NULL,
    "status" "PassportExternalPendingStatus" NOT NULL DEFAULT 'pending',
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_external_pending_identities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_external_pending_qr_states" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "pending_identity_hash" TEXT NOT NULL,
    "qr_state_hash" TEXT NOT NULL,

    CONSTRAINT "passport_external_pending_qr_states_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_external_providers" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "provider" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "client_secret" TEXT NOT NULL,
    "status" "PassportAccountStatus" NOT NULL DEFAULT 'enabled',
    "wechat_mode" TEXT NOT NULL DEFAULT 'open_platform',
    "wechat_redirect_domain" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "passport_external_providers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_oidc_clients" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "client_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "secret_hash" TEXT NOT NULL,
    "redirect_uris" TEXT NOT NULL DEFAULT '[]',
    "allowed_scopes" TEXT NOT NULL DEFAULT 'openid profile email',
    "require_pkce" BOOLEAN NOT NULL DEFAULT true,
    "status" "PassportAccountStatus" NOT NULL DEFAULT 'enabled',
    "backchannel_logout_uri" TEXT NOT NULL DEFAULT '',
    "strict_redirect_uri" BOOLEAN NOT NULL DEFAULT false,
    "password_sync" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "passport_oidc_clients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_oidc_authorization_requests" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "request_id" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "redirect_uri" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT '',
    "nonce" TEXT NOT NULL DEFAULT '',
    "code_challenge" TEXT NOT NULL DEFAULT '',
    "code_challenge_method" TEXT NOT NULL DEFAULT '',
    "expires_at" BIGINT NOT NULL,

    CONSTRAINT "passport_oidc_authorization_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_oidc_authorization_codes" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "code_hash" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "redirect_uri" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "nonce" TEXT NOT NULL DEFAULT '',
    "code_challenge" TEXT NOT NULL DEFAULT '',
    "code_challenge_method" TEXT NOT NULL DEFAULT '',
    "expires_at" BIGINT NOT NULL,
    "consumed_at" BIGINT,
    "session_id" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "passport_oidc_authorization_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_oidc_access_tokens" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "token_hash" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "user_key" VARCHAR(36) NOT NULL,
    "scope" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,
    "session_id" TEXT NOT NULL DEFAULT '',
    "authorization_code_hash" TEXT,

    CONSTRAINT "passport_oidc_access_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_oidc_signing_keys" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "kid" TEXT NOT NULL,
    "private_jwk" TEXT NOT NULL,
    "public_jwk" TEXT NOT NULL,
    "status" "PassportSigningKeyStatus" NOT NULL DEFAULT 'active',

    CONSTRAINT "passport_oidc_signing_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passport_user_profiles" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "user_key" VARCHAR(36) NOT NULL,
    "nickname" TEXT,
    "qq" TEXT NOT NULL DEFAULT '',
    "wechat" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "passport_user_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "passport_users_key_key" ON "passport_users"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_users_name_deleted_at_key" ON "passport_users"("name", "deleted_at");

-- CreateIndex
CREATE INDEX "passport_user_email_otps_user_key_status_created_at_idx" ON "passport_user_email_otps"("user_key", "status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_email_otps_otp_id_key" ON "passport_user_email_otps"("otp_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_email_otps_key_key" ON "passport_user_email_otps"("key");

-- CreateIndex
CREATE INDEX "passport_user_credentials_user_key_created_at_id_idx" ON "passport_user_credentials"("user_key", "created_at", "id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_credentials_key_key" ON "passport_user_credentials"("key");

-- CreateIndex
CREATE INDEX "passport_sessions_user_key_idx" ON "passport_sessions"("user_key");

-- CreateIndex
CREATE INDEX "passport_sessions_expires_at_idx" ON "passport_sessions"("expires_at");

-- CreateIndex
CREATE INDEX "passport_sessions_device_id_idx" ON "passport_sessions"("device_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_sessions_token_hash_key" ON "passport_sessions"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_sessions_key_key" ON "passport_sessions"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_devices_key_key" ON "passport_devices"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_device_users_device_id_user_key_key" ON "passport_device_users"("device_id", "user_key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_device_users_key_key" ON "passport_device_users"("key");

-- CreateIndex
CREATE INDEX "passport_telegram_accounts_user_key_idx" ON "passport_telegram_accounts"("user_key");

-- CreateIndex
CREATE INDEX "passport_telegram_accounts_chat_id_idx" ON "passport_telegram_accounts"("chat_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_accounts_bot_id_telegram_user_id_key" ON "passport_telegram_accounts"("bot_id", "telegram_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_accounts_key_key" ON "passport_telegram_accounts"("key");

-- CreateIndex
CREATE INDEX "passport_oauth_accounts_user_key_idx" ON "passport_oauth_accounts"("user_key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oauth_accounts_provider_provider_user_id_key" ON "passport_oauth_accounts"("provider", "provider_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oauth_accounts_key_key" ON "passport_oauth_accounts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_emails_email_key" ON "passport_emails"("email");

-- CreateIndex
CREATE UNIQUE INDEX "passport_emails_key_key" ON "passport_emails"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_emails_user_key_email_id_key" ON "passport_user_emails"("user_key", "email_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_emails_email_id_key" ON "passport_user_emails"("email_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_emails_key_key" ON "passport_user_emails"("key");

-- CreateIndex
CREATE INDEX "passport_telegram_email_otps_bot_id_telegram_user_id_status_idx" ON "passport_telegram_email_otps"("bot_id", "telegram_user_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "passport_telegram_email_otps_chat_id_idx" ON "passport_telegram_email_otps"("chat_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_email_otps_key_key" ON "passport_telegram_email_otps"("key");

-- CreateIndex
CREATE INDEX "passport_telegram_menus_chat_id_idx" ON "passport_telegram_menus"("chat_id");

-- CreateIndex
CREATE INDEX "passport_telegram_menus_message_id_idx" ON "passport_telegram_menus"("message_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_menus_bot_id_telegram_user_id_key" ON "passport_telegram_menus"("bot_id", "telegram_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_menus_key_key" ON "passport_telegram_menus"("key");

-- CreateIndex
CREATE INDEX "passport_telegram_updates_status_updated_at_idx" ON "passport_telegram_updates"("status", "updated_at");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_updates_bot_id_update_id_key" ON "passport_telegram_updates"("bot_id", "update_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_updates_key_key" ON "passport_telegram_updates"("key");

-- CreateIndex
CREATE INDEX "passport_telegram_identity_choices_bot_id_telegram_user_id__idx" ON "passport_telegram_identity_choices"("bot_id", "telegram_user_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "passport_telegram_identity_choices_chat_id_idx" ON "passport_telegram_identity_choices"("chat_id");

-- CreateIndex
CREATE INDEX "passport_telegram_identity_choices_target_user_key_idx" ON "passport_telegram_identity_choices"("target_user_key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_identity_choices_key_key" ON "passport_telegram_identity_choices"("key");

-- CreateIndex
CREATE INDEX "passport_login_challenges_bot_id_telegram_user_id_status_cr_idx" ON "passport_login_challenges"("bot_id", "telegram_user_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "passport_login_challenges_status_expires_at_idx" ON "passport_login_challenges"("status", "expires_at");

-- CreateIndex
CREATE INDEX "passport_login_challenges_user_key_idx" ON "passport_login_challenges"("user_key");

-- CreateIndex
CREATE INDEX "passport_login_challenges_chat_id_idx" ON "passport_login_challenges"("chat_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_login_challenges_challenge_id_key" ON "passport_login_challenges"("challenge_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_login_challenges_key_key" ON "passport_login_challenges"("key");

-- CreateIndex
CREATE INDEX "passport_sso_requests_status_expires_at_idx" ON "passport_sso_requests"("status", "expires_at");

-- CreateIndex
CREATE INDEX "passport_sso_requests_target_site_key_idx" ON "passport_sso_requests"("target_site_key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_sso_requests_request_id_key" ON "passport_sso_requests"("request_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_sso_requests_key_key" ON "passport_sso_requests"("key");

-- CreateIndex
CREATE INDEX "passport_login_tickets_status_expires_at_idx" ON "passport_login_tickets"("status", "expires_at");

-- CreateIndex
CREATE INDEX "passport_login_tickets_user_key_idx" ON "passport_login_tickets"("user_key");

-- CreateIndex
CREATE INDEX "passport_login_tickets_target_site_key_idx" ON "passport_login_tickets"("target_site_key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_login_tickets_token_hash_key" ON "passport_login_tickets"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_login_tickets_key_key" ON "passport_login_tickets"("key");

-- CreateIndex
CREATE INDEX "passport_site_sessions_user_key_idx" ON "passport_site_sessions"("user_key");

-- CreateIndex
CREATE INDEX "passport_site_sessions_site_key_hostname_expires_at_idx" ON "passport_site_sessions"("site_key", "hostname", "expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "passport_site_sessions_session_id_key" ON "passport_site_sessions"("session_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_site_sessions_key_key" ON "passport_site_sessions"("key");

-- CreateIndex
CREATE INDEX "passport_group_prompts_chat_id_actor_id_updated_at_idx" ON "passport_group_prompts"("chat_id", "actor_id", "updated_at");

-- CreateIndex
CREATE UNIQUE INDEX "passport_group_prompts_key_key" ON "passport_group_prompts"("key");

-- CreateIndex
CREATE INDEX "passport_external_email_otps_pending_identity_hash_status_c_idx" ON "passport_external_email_otps"("pending_identity_hash", "status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_email_otps_otp_id_key" ON "passport_external_email_otps"("otp_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_email_otps_key_key" ON "passport_external_email_otps"("key");

-- CreateIndex
CREATE INDEX "passport_external_identities_user_key_idx" ON "passport_external_identities"("user_key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_identities_provider_subject_key" ON "passport_external_identities"("provider", "subject");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_identities_key_key" ON "passport_external_identities"("key");

-- CreateIndex
CREATE INDEX "passport_external_login_states_expires_at_consumed_at_idx" ON "passport_external_login_states"("expires_at", "consumed_at");

-- CreateIndex
CREATE INDEX "passport_external_login_states_qr_user_key_idx" ON "passport_external_login_states"("qr_user_key");

-- CreateIndex
CREATE INDEX "passport_external_login_states_oidc_request_id_idx" ON "passport_external_login_states"("oidc_request_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_login_states_id_hash_key" ON "passport_external_login_states"("id_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_login_states_key_key" ON "passport_external_login_states"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_pending_identities_id_hash_key" ON "passport_external_pending_identities"("id_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_pending_identities_key_key" ON "passport_external_pending_identities"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_pending_qr_states_pending_identity_hash_key" ON "passport_external_pending_qr_states"("pending_identity_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_pending_qr_states_qr_state_hash_key" ON "passport_external_pending_qr_states"("qr_state_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_pending_qr_states_key_key" ON "passport_external_pending_qr_states"("key");

-- CreateIndex
CREATE INDEX "passport_external_providers_client_id_idx" ON "passport_external_providers"("client_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_providers_provider_key" ON "passport_external_providers"("provider");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_providers_key_key" ON "passport_external_providers"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_clients_client_id_key" ON "passport_oidc_clients"("client_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_clients_key_key" ON "passport_oidc_clients"("key");

-- CreateIndex
CREATE INDEX "passport_oidc_authorization_requests_client_id_idx" ON "passport_oidc_authorization_requests"("client_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_authorization_requests_request_id_key" ON "passport_oidc_authorization_requests"("request_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_authorization_requests_key_key" ON "passport_oidc_authorization_requests"("key");

-- CreateIndex
CREATE INDEX "passport_oidc_authorization_codes_expires_at_consumed_at_idx" ON "passport_oidc_authorization_codes"("expires_at", "consumed_at");

-- CreateIndex
CREATE INDEX "passport_oidc_authorization_codes_client_id_idx" ON "passport_oidc_authorization_codes"("client_id");

-- CreateIndex
CREATE INDEX "passport_oidc_authorization_codes_user_key_idx" ON "passport_oidc_authorization_codes"("user_key");

-- CreateIndex
CREATE INDEX "passport_oidc_authorization_codes_session_id_idx" ON "passport_oidc_authorization_codes"("session_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_authorization_codes_code_hash_key" ON "passport_oidc_authorization_codes"("code_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_authorization_codes_key_key" ON "passport_oidc_authorization_codes"("key");

-- CreateIndex
CREATE INDEX "passport_oidc_access_tokens_expires_at_revoked_at_idx" ON "passport_oidc_access_tokens"("expires_at", "revoked_at");

-- CreateIndex
CREATE INDEX "passport_oidc_access_tokens_client_id_idx" ON "passport_oidc_access_tokens"("client_id");

-- CreateIndex
CREATE INDEX "passport_oidc_access_tokens_user_key_idx" ON "passport_oidc_access_tokens"("user_key");

-- CreateIndex
CREATE INDEX "passport_oidc_access_tokens_session_id_idx" ON "passport_oidc_access_tokens"("session_id");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_access_tokens_token_hash_key" ON "passport_oidc_access_tokens"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_access_tokens_authorization_code_hash_key" ON "passport_oidc_access_tokens"("authorization_code_hash");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_access_tokens_key_key" ON "passport_oidc_access_tokens"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_signing_keys_kid_key" ON "passport_oidc_signing_keys"("kid");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_signing_keys_key_key" ON "passport_oidc_signing_keys"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_profiles_user_key_key" ON "passport_user_profiles"("user_key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_profiles_key_key" ON "passport_user_profiles"("key");
