-- Generated by Prisma migrate diff. Source: prisma/passport.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterTable
ALTER TABLE "passport_external_providers" DROP COLUMN "display_name",
ADD COLUMN     "title" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "passport_oidc_clients" DROP COLUMN "name",
ADD COLUMN     "title" TEXT NOT NULL;
