-- Generated by Prisma migrate diff. Source: prisma/passport.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "passport_users_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_user_email_otps_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_user_credentials_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_sessions_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_devices_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_device_users_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_telegram_accounts_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_oauth_accounts_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_emails_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_user_emails_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_email_otp_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_telegram_menus_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_telegram_updates_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_telegram_identity_choices_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_login_challenges_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_sso_requests_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_login_tickets_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_site_sessions_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_group_prompts_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_external_email_otps_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_external_identities_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_external_login_states_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_external_pending_identities_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_external_pending_qr_states_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_external_providers_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_oidc_clients_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_oidc_authorization_requests_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_oidc_authorization_codes_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_oidc_access_tokens_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_oidc_signing_keys_key_deleted_at_key";

-- DropIndex
DROP INDEX "passport_user_profiles_key_deleted_at_key";

-- CreateIndex
CREATE UNIQUE INDEX "passport_users_key_key" ON "passport_users"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_email_otps_key_key" ON "passport_user_email_otps"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_credentials_key_key" ON "passport_user_credentials"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_sessions_key_key" ON "passport_sessions"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_devices_key_key" ON "passport_devices"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_device_users_key_key" ON "passport_device_users"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_accounts_key_key" ON "passport_telegram_accounts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oauth_accounts_key_key" ON "passport_oauth_accounts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_emails_key_key" ON "passport_emails"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_emails_key_key" ON "passport_user_emails"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_email_otp_key_key" ON "passport_email_otp"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_menus_key_key" ON "passport_telegram_menus"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_updates_key_key" ON "passport_telegram_updates"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_telegram_identity_choices_key_key" ON "passport_telegram_identity_choices"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_login_challenges_key_key" ON "passport_login_challenges"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_sso_requests_key_key" ON "passport_sso_requests"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_login_tickets_key_key" ON "passport_login_tickets"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_site_sessions_key_key" ON "passport_site_sessions"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_group_prompts_key_key" ON "passport_group_prompts"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_email_otps_key_key" ON "passport_external_email_otps"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_identities_key_key" ON "passport_external_identities"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_login_states_key_key" ON "passport_external_login_states"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_pending_identities_key_key" ON "passport_external_pending_identities"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_pending_qr_states_key_key" ON "passport_external_pending_qr_states"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_external_providers_key_key" ON "passport_external_providers"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_clients_key_key" ON "passport_oidc_clients"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_authorization_requests_key_key" ON "passport_oidc_authorization_requests"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_authorization_codes_key_key" ON "passport_oidc_authorization_codes"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_access_tokens_key_key" ON "passport_oidc_access_tokens"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_oidc_signing_keys_key_key" ON "passport_oidc_signing_keys"("key");

-- CreateIndex
CREATE UNIQUE INDEX "passport_user_profiles_key_key" ON "passport_user_profiles"("key");
