-- Generated by Prisma migrate diff. Source: prisma/passport.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateTable
CREATE TABLE `passport_users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',

    UNIQUE INDEX `passport_users_user_id_deleted_at_key`(`user_id`, `deleted_at`),
    UNIQUE INDEX `passport_users_name_deleted_at_key`(`name`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_user_email_otps` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `otp_id` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `code_hash` VARCHAR(191) NOT NULL,
    `attempt_count` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('pending', 'expired', 'used') NOT NULL DEFAULT 'pending',
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_user_email_otps_user_id_status_created_at_idx`(`user_id`, `status`, `created_at`),
    UNIQUE INDEX `passport_user_email_otps_otp_id_deleted_at_key`(`otp_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_user_credentials` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `password` JSON NOT NULL,

    INDEX `passport_user_credentials_user_id_created_at_id_idx`(`user_id`, `created_at`, `id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_sessions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `token_hash` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `expires_at` BIGINT NOT NULL,
    `device_id` BIGINT NOT NULL,

    INDEX `passport_sessions_user_id_idx`(`user_id`),
    INDEX `passport_sessions_expires_at_idx`(`expires_at`),
    UNIQUE INDEX `passport_sessions_token_hash_deleted_at_key`(`token_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_devices` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `key` VARCHAR(191) NOT NULL,
    `fingerprint` JSON NOT NULL,
    `user_agent` VARCHAR(191) NOT NULL DEFAULT '',
    `platform` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_address` VARCHAR(191) NOT NULL DEFAULT '',
    `network_info` JSON NOT NULL,
    `status` ENUM('active', 'revoked') NOT NULL DEFAULT 'active',
    `last_seen_at` BIGINT NOT NULL,
    `revoked_at` BIGINT NULL,

    UNIQUE INDEX `passport_devices_key_deleted_at_key`(`key`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_device_users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `device_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `status` ENUM('active', 'revoked') NOT NULL DEFAULT 'active',
    `last_seen_at` BIGINT NOT NULL,
    `revoked_at` BIGINT NULL,

    UNIQUE INDEX `passport_device_users_device_id_user_id_deleted_at_key`(`device_id`, `user_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_telegram_accounts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `bot_id` BIGINT NOT NULL,
    `telegram_user_id` BIGINT NOT NULL,
    `chat_id` BIGINT NOT NULL,
    `nickname` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `passport_telegram_accounts_bot_id_telegram_user_id_deleted_a_key`(`bot_id`, `telegram_user_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_oauth_accounts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `provider_user_id` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `passport_oauth_accounts_provider_provider_user_id_deleted_at_key`(`provider`, `provider_user_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_emails` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `email` VARCHAR(191) NOT NULL,
    `verified` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `passport_emails_email_deleted_at_key`(`email`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_user_emails` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `email_id` BIGINT NOT NULL,
    `is_primary` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `passport_user_emails_user_id_email_id_deleted_at_key`(`user_id`, `email_id`, `deleted_at`),
    UNIQUE INDEX `passport_user_emails_email_id_deleted_at_key`(`email_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_email_otp` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `bot_id` BIGINT NOT NULL,
    `telegram_user_id` BIGINT NOT NULL,
    `chat_id` BIGINT NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `code_hash` VARCHAR(191) NOT NULL,
    `attempt_count` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('pending', 'expired', 'used') NOT NULL DEFAULT 'pending',
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_email_otp_bot_id_telegram_user_id_status_created_at_idx`(`bot_id`, `telegram_user_id`, `status`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_snowflake_state` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `worker_id` INTEGER NOT NULL,
    `last_timestamp` BIGINT NOT NULL,

    UNIQUE INDEX `passport_snowflake_state_worker_id_deleted_at_key`(`worker_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_telegram_menus` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `bot_id` BIGINT NOT NULL,
    `telegram_user_id` BIGINT NOT NULL,
    `chat_id` BIGINT NOT NULL,
    `message_id` BIGINT NOT NULL,
    `mode` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `passport_telegram_menus_bot_id_telegram_user_id_deleted_at_key`(`bot_id`, `telegram_user_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_telegram_updates` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `bot_id` BIGINT NOT NULL,
    `update_id` BIGINT NOT NULL,
    `status` ENUM('processing', 'completed', 'failed') NOT NULL,

    INDEX `passport_telegram_updates_status_updated_at_idx`(`status`, `updated_at`),
    UNIQUE INDEX `passport_telegram_updates_bot_id_update_id_deleted_at_key`(`bot_id`, `update_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_telegram_identity_choices` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `bot_id` BIGINT NOT NULL,
    `telegram_user_id` BIGINT NOT NULL,
    `chat_id` BIGINT NOT NULL,
    `target_user_id` BIGINT NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `status` ENUM('pending', 'confirmed', 'cancelled', 'expired') NOT NULL,
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_telegram_identity_choices_bot_id_telegram_user_id_s_idx`(`bot_id`, `telegram_user_id`, `status`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_login_challenges` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `challenge_id` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `bot_id` BIGINT NOT NULL,
    `telegram_user_id` BIGINT NOT NULL,
    `chat_id` BIGINT NOT NULL,
    `expected_number` INTEGER NOT NULL,
    `status` ENUM('pending', 'approved', 'denied', 'consumed', 'expired') NOT NULL,
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_login_challenges_bot_id_telegram_user_id_status_cre_idx`(`bot_id`, `telegram_user_id`, `status`, `created_at`),
    INDEX `passport_login_challenges_status_expires_at_idx`(`status`, `expires_at`),
    UNIQUE INDEX `passport_login_challenges_challenge_id_deleted_at_key`(`challenge_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_sso_requests` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `request_id` VARCHAR(191) NOT NULL,
    `target_site_key` VARCHAR(191) NOT NULL,
    `target_hostname` VARCHAR(191) NOT NULL,
    `status` ENUM('pending', 'consumed', 'expired') NOT NULL,
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_sso_requests_status_expires_at_idx`(`status`, `expires_at`),
    UNIQUE INDEX `passport_sso_requests_request_id_deleted_at_key`(`request_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_login_tickets` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `token_hash` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `target_site_key` VARCHAR(191) NOT NULL,
    `target_hostname` VARCHAR(191) NOT NULL,
    `status` ENUM('pending', 'consumed', 'expired') NOT NULL,
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_login_tickets_status_expires_at_idx`(`status`, `expires_at`),
    UNIQUE INDEX `passport_login_tickets_token_hash_deleted_at_key`(`token_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_site_sessions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `session_id` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `site_key` VARCHAR(191) NOT NULL,
    `hostname` VARCHAR(191) NOT NULL,
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_site_sessions_user_id_idx`(`user_id`),
    INDEX `passport_site_sessions_site_key_hostname_expires_at_idx`(`site_key`, `hostname`, `expires_at`),
    UNIQUE INDEX `passport_site_sessions_session_id_deleted_at_key`(`session_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_group_prompts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `chat_id` BIGINT NOT NULL,
    `actor_id` BIGINT NOT NULL,
    `state_json` VARCHAR(191) NOT NULL DEFAULT '{}',
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_group_prompts_chat_id_actor_id_updated_at_idx`(`chat_id`, `actor_id`, `updated_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_external_email_otps` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `otp_id` VARCHAR(191) NOT NULL,
    `pending_identity_hash` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `code_hash` VARCHAR(191) NOT NULL,
    `attempt_count` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('pending', 'expired', 'used') NOT NULL DEFAULT 'pending',
    `expires_at` BIGINT NOT NULL,

    INDEX `passport_external_email_otps_pending_identity_hash_status_cr_idx`(`pending_identity_hash`, `status`, `created_at`),
    UNIQUE INDEX `passport_external_email_otps_otp_id_deleted_at_key`(`otp_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_external_identities` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `subject` VARCHAR(191) NOT NULL,
    `profile` VARCHAR(191) NOT NULL DEFAULT '{}',

    INDEX `passport_external_identities_user_id_idx`(`user_id`),
    UNIQUE INDEX `passport_external_identities_provider_subject_deleted_at_key`(`provider`, `subject`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_external_login_states` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `id_hash` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `code_verifier` VARCHAR(191) NOT NULL,
    `nonce` VARCHAR(191) NOT NULL,
    `redirect_uri` VARCHAR(191) NOT NULL,
    `expires_at` BIGINT NOT NULL,
    `consumed_at` BIGINT NULL,
    `qr_status` ENUM('pending', 'authorized', 'consumed') NOT NULL DEFAULT 'pending',
    `qr_user_id` VARCHAR(191) NULL,
    `oidc_request_id` VARCHAR(191) NULL,

    INDEX `passport_external_login_states_expires_at_consumed_at_idx`(`expires_at`, `consumed_at`),
    UNIQUE INDEX `passport_external_login_states_id_hash_deleted_at_key`(`id_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_external_pending_identities` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `id_hash` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `subject` VARCHAR(191) NOT NULL,
    `nickname` VARCHAR(191) NOT NULL,
    `profile` VARCHAR(191) NOT NULL,
    `status` ENUM('pending', 'expired', 'completed') NOT NULL DEFAULT 'pending',
    `expires_at` BIGINT NOT NULL,

    UNIQUE INDEX `passport_external_pending_identities_id_hash_deleted_at_key`(`id_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_external_pending_qr_states` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `pending_identity_hash` VARCHAR(191) NOT NULL,
    `qr_state_hash` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `passport_external_pending_qr_states_pending_identity_hash_de_key`(`pending_identity_hash`, `deleted_at`),
    UNIQUE INDEX `passport_external_pending_qr_states_qr_state_hash_deleted_at_key`(`qr_state_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_external_providers` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `display_name` VARCHAR(191) NOT NULL,
    `client_id` VARCHAR(191) NOT NULL,
    `client_secret` VARCHAR(191) NOT NULL,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `wechat_mode` VARCHAR(191) NOT NULL DEFAULT 'open_platform',
    `wechat_redirect_domain` VARCHAR(191) NOT NULL DEFAULT '',

    UNIQUE INDEX `passport_external_providers_provider_deleted_at_key`(`provider`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_oidc_clients` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `client_id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `secret_hash` VARCHAR(191) NOT NULL,
    `redirect_uris` VARCHAR(191) NOT NULL DEFAULT '[]',
    `allowed_scopes` VARCHAR(191) NOT NULL DEFAULT 'openid profile email',
    `require_pkce` INTEGER NOT NULL DEFAULT 1,
    `status` ENUM('enabled', 'disabled') NOT NULL DEFAULT 'enabled',
    `backchannel_logout_uri` VARCHAR(191) NOT NULL DEFAULT '',
    `strict_redirect_uri` INTEGER NOT NULL DEFAULT 0,
    `password_sync` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `passport_oidc_clients_client_id_deleted_at_key`(`client_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_oidc_authorization_requests` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `request_id` VARCHAR(191) NOT NULL,
    `client_id` VARCHAR(191) NOT NULL,
    `redirect_uri` VARCHAR(191) NOT NULL,
    `scope` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL DEFAULT '',
    `nonce` VARCHAR(191) NOT NULL DEFAULT '',
    `code_challenge` VARCHAR(191) NOT NULL DEFAULT '',
    `code_challenge_method` VARCHAR(191) NOT NULL DEFAULT '',
    `expires_at` BIGINT NOT NULL,

    UNIQUE INDEX `passport_oidc_authorization_requests_request_id_deleted_at_key`(`request_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_oidc_authorization_codes` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `code_hash` VARCHAR(191) NOT NULL,
    `client_id` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `redirect_uri` VARCHAR(191) NOT NULL,
    `scope` VARCHAR(191) NOT NULL,
    `nonce` VARCHAR(191) NOT NULL DEFAULT '',
    `code_challenge` VARCHAR(191) NOT NULL DEFAULT '',
    `code_challenge_method` VARCHAR(191) NOT NULL DEFAULT '',
    `expires_at` BIGINT NOT NULL,
    `consumed_at` BIGINT NULL,
    `session_id` VARCHAR(191) NOT NULL DEFAULT '',

    INDEX `passport_oidc_authorization_codes_expires_at_consumed_at_idx`(`expires_at`, `consumed_at`),
    UNIQUE INDEX `passport_oidc_authorization_codes_code_hash_deleted_at_key`(`code_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_oidc_access_tokens` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `token_hash` VARCHAR(191) NOT NULL,
    `client_id` VARCHAR(191) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `scope` VARCHAR(191) NOT NULL,
    `expires_at` BIGINT NOT NULL,
    `revoked_at` BIGINT NULL,
    `session_id` VARCHAR(191) NOT NULL DEFAULT '',
    `authorization_code_hash` VARCHAR(191) NULL,

    INDEX `passport_oidc_access_tokens_expires_at_revoked_at_idx`(`expires_at`, `revoked_at`),
    UNIQUE INDEX `passport_oidc_access_tokens_token_hash_deleted_at_key`(`token_hash`, `deleted_at`),
    UNIQUE INDEX `passport_oidc_access_tokens_authorization_code_hash_deleted__key`(`authorization_code_hash`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_oidc_signing_keys` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `kid` VARCHAR(191) NOT NULL,
    `private_jwk` VARCHAR(191) NOT NULL,
    `public_jwk` VARCHAR(191) NOT NULL,
    `status` ENUM('active', 'retired') NOT NULL DEFAULT 'active',

    UNIQUE INDEX `passport_oidc_signing_keys_kid_deleted_at_key`(`kid`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passport_user_profiles` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `created_duid` BIGINT NULL,
    `updated_duid` BIGINT NULL,
    `owner_tid` BIGINT NOT NULL DEFAULT 1,
    `owner_bid` BIGINT NOT NULL DEFAULT 1,
    `owner_uid` BIGINT NULL,
    `user_id` BIGINT NOT NULL,
    `nickname` VARCHAR(191) NULL,
    `qq` VARCHAR(191) NOT NULL DEFAULT '',
    `wechat` VARCHAR(191) NOT NULL DEFAULT '',

    UNIQUE INDEX `passport_user_profiles_user_id_deleted_at_key`(`user_id`, `deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
