-- Generated by Prisma migrate diff. Source: prisma/passport.prisma (mysql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX `passport_user_email_otps_otp_id_deleted_at_key` ON `passport_user_email_otps`;

-- DropIndex
DROP INDEX `passport_sessions_token_hash_deleted_at_key` ON `passport_sessions`;

-- DropIndex
DROP INDEX `passport_device_users_device_id_user_key_deleted_at_key` ON `passport_device_users`;

-- DropIndex
DROP INDEX `passport_telegram_accounts_bot_id_telegram_user_id_deleted_a_key` ON `passport_telegram_accounts`;

-- DropIndex
DROP INDEX `passport_oauth_accounts_provider_provider_user_id_deleted_at_key` ON `passport_oauth_accounts`;

-- DropIndex
DROP INDEX `passport_emails_email_deleted_at_key` ON `passport_emails`;

-- DropIndex
DROP INDEX `passport_user_emails_user_key_email_id_deleted_at_key` ON `passport_user_emails`;

-- DropIndex
DROP INDEX `passport_user_emails_email_id_deleted_at_key` ON `passport_user_emails`;

-- DropIndex
DROP INDEX `passport_telegram_menus_bot_id_telegram_user_id_deleted_at_key` ON `passport_telegram_menus`;

-- DropIndex
DROP INDEX `passport_telegram_updates_bot_id_update_id_deleted_at_key` ON `passport_telegram_updates`;

-- DropIndex
DROP INDEX `passport_login_challenges_challenge_id_deleted_at_key` ON `passport_login_challenges`;

-- DropIndex
DROP INDEX `passport_sso_requests_request_id_deleted_at_key` ON `passport_sso_requests`;

-- DropIndex
DROP INDEX `passport_login_tickets_token_hash_deleted_at_key` ON `passport_login_tickets`;

-- DropIndex
DROP INDEX `passport_site_sessions_session_id_deleted_at_key` ON `passport_site_sessions`;

-- DropIndex
DROP INDEX `passport_external_email_otps_otp_id_deleted_at_key` ON `passport_external_email_otps`;

-- DropIndex
DROP INDEX `passport_external_identities_provider_subject_deleted_at_key` ON `passport_external_identities`;

-- DropIndex
DROP INDEX `passport_external_login_states_id_hash_deleted_at_key` ON `passport_external_login_states`;

-- DropIndex
DROP INDEX `passport_external_pending_identities_id_hash_deleted_at_key` ON `passport_external_pending_identities`;

-- DropIndex
DROP INDEX `passport_external_pending_qr_states_pending_identity_hash_de_key` ON `passport_external_pending_qr_states`;

-- DropIndex
DROP INDEX `passport_external_pending_qr_states_qr_state_hash_deleted_at_key` ON `passport_external_pending_qr_states`;

-- DropIndex
DROP INDEX `passport_external_providers_provider_deleted_at_key` ON `passport_external_providers`;

-- DropIndex
DROP INDEX `passport_oidc_clients_client_id_deleted_at_key` ON `passport_oidc_clients`;

-- DropIndex
DROP INDEX `passport_oidc_authorization_requests_request_id_deleted_at_key` ON `passport_oidc_authorization_requests`;

-- DropIndex
DROP INDEX `passport_oidc_authorization_codes_code_hash_deleted_at_key` ON `passport_oidc_authorization_codes`;

-- DropIndex
DROP INDEX `passport_oidc_access_tokens_token_hash_deleted_at_key` ON `passport_oidc_access_tokens`;

-- DropIndex
DROP INDEX `passport_oidc_access_tokens_authorization_code_hash_deleted__key` ON `passport_oidc_access_tokens`;

-- DropIndex
DROP INDEX `passport_oidc_signing_keys_kid_deleted_at_key` ON `passport_oidc_signing_keys`;

-- DropIndex
DROP INDEX `passport_user_profiles_user_key_deleted_at_key` ON `passport_user_profiles`;

-- CreateIndex
CREATE UNIQUE INDEX `passport_user_email_otps_otp_id_key` ON `passport_user_email_otps`(`otp_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_sessions_token_hash_key` ON `passport_sessions`(`token_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_device_users_device_id_user_key_key` ON `passport_device_users`(`device_id`, `user_key`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_telegram_accounts_bot_id_telegram_user_id_key` ON `passport_telegram_accounts`(`bot_id`, `telegram_user_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_oauth_accounts_provider_provider_user_id_key` ON `passport_oauth_accounts`(`provider`, `provider_user_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_emails_email_key` ON `passport_emails`(`email`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_user_emails_user_key_email_id_key` ON `passport_user_emails`(`user_key`, `email_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_user_emails_email_id_key` ON `passport_user_emails`(`email_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_telegram_menus_bot_id_telegram_user_id_key` ON `passport_telegram_menus`(`bot_id`, `telegram_user_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_telegram_updates_bot_id_update_id_key` ON `passport_telegram_updates`(`bot_id`, `update_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_login_challenges_challenge_id_key` ON `passport_login_challenges`(`challenge_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_sso_requests_request_id_key` ON `passport_sso_requests`(`request_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_login_tickets_token_hash_key` ON `passport_login_tickets`(`token_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_site_sessions_session_id_key` ON `passport_site_sessions`(`session_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_external_email_otps_otp_id_key` ON `passport_external_email_otps`(`otp_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_external_identities_provider_subject_key` ON `passport_external_identities`(`provider`, `subject`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_external_login_states_id_hash_key` ON `passport_external_login_states`(`id_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_external_pending_identities_id_hash_key` ON `passport_external_pending_identities`(`id_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_external_pending_qr_states_pending_identity_hash_key` ON `passport_external_pending_qr_states`(`pending_identity_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_external_pending_qr_states_qr_state_hash_key` ON `passport_external_pending_qr_states`(`qr_state_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_external_providers_provider_key` ON `passport_external_providers`(`provider`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_oidc_clients_client_id_key` ON `passport_oidc_clients`(`client_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_oidc_authorization_requests_request_id_key` ON `passport_oidc_authorization_requests`(`request_id`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_oidc_authorization_codes_code_hash_key` ON `passport_oidc_authorization_codes`(`code_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_oidc_access_tokens_token_hash_key` ON `passport_oidc_access_tokens`(`token_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_oidc_access_tokens_authorization_code_hash_key` ON `passport_oidc_access_tokens`(`authorization_code_hash`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_oidc_signing_keys_kid_key` ON `passport_oidc_signing_keys`(`kid`);

-- CreateIndex
CREATE UNIQUE INDEX `passport_user_profiles_user_key_key` ON `passport_user_profiles`(`user_key`);
