-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- CreateEnum
CREATE TYPE "SmsPlatformKeyStatus" AS ENUM ('active', 'retiring', 'retired');

-- CreateTable
CREATE TABLE "sms_platform_keys" (
    "id" BIGSERIAL NOT NULL,
    "key" VARCHAR(36) NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT 0,
    "updated_at" BIGINT NOT NULL DEFAULT 0,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "queued_at" BIGINT NOT NULL DEFAULT 0,
    "created_duid" BIGINT,
    "updated_duid" BIGINT,
    "owner_tid" BIGINT NOT NULL DEFAULT 1,
    "owner_bid" BIGINT NOT NULL DEFAULT 1,
    "owner_uid" BIGINT,
    "kid" VARCHAR(32) NOT NULL,
    "public_key" VARCHAR(64) NOT NULL,
    "private_key" TEXT NOT NULL,
    "status" "SmsPlatformKeyStatus" NOT NULL DEFAULT 'active',
    "retired_at" BIGINT,

    CONSTRAINT "sms_platform_keys_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "sms_platform_keys_key_key" ON "sms_platform_keys"("key");

-- CreateIndex
CREATE UNIQUE INDEX "sms_platform_keys_kid_key" ON "sms_platform_keys"("kid");
