-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "sms_phones_owner_tid_number_deleted_at_key";

-- AlterTable
ALTER TABLE "sms_phones" ADD COLUMN     "integration_client_id" BIGINT NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX "sms_phones_integration_client_id_idx" ON "sms_phones"("integration_client_id");

-- CreateIndex
CREATE UNIQUE INDEX "sms_phones_owner_tid_owner_uid_integration_client_id_number_key" ON "sms_phones"("owner_tid", "owner_uid", "integration_client_id", "number", "deleted_at");
