-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- DropIndex
DROP INDEX "sms_phones_owner_tid_owner_uid_integration_client_id_number_key";

-- AlterTable
ALTER TABLE "sms_phones" ADD COLUMN     "client_ref" TEXT NOT NULL DEFAULT '';

-- CreateIndex
CREATE UNIQUE INDEX "sms_phones_owner_tid_owner_uid_integration_client_id_client_key" ON "sms_phones"("owner_tid", "owner_uid", "integration_client_id", "client_ref", "number", "deleted_at");
