-- Generated by Prisma migrate diff. Source: prisma/sms.prisma (postgresql).
-- Do not edit this file directly; update the Prisma schema and rerun npm run prisma:migrations.

-- AlterEnum
ALTER TYPE "SmsPlatformKeyStatus" ADD VALUE 'publishing';
